wri/wri-terramatch-website

- src/components/extensive/ActionTracker/cards/ReportsCard.tsx
filter out actions when target is null on report actions to prevent home page from crashing
> filter out actions when target is null on report action cards

- src/helpers/customForms.ts
Added support for conditional fields in normalizedFormData to fix InputTable value not saving when added as conditional input children.
> 🟢 hotfix/TM-462-normalize-form-data-fix [Small]

- src/admin/modules/form/components/CopyFormToOtherEnv.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-535)
Updated references to new environments and add a dropdown for framework selection.
> fix: TM-535 update references to copy across envs

- src/components/extensive/ActionTracker/ActionTrackerCard.tsx
- src/components/extensive/ActionTracker/cards/ProjectsCard.tsx
[Task](https://gfw.atlassian.net/browse/TM-520)
Adding a new node in the list of project for awaiting approval projects
> TM-520 create action track node draft

- src/generated/apiComponents.ts
- src/generated/apiRequestBodies.ts
- src/generated/apiSchemas.ts
> chore: update api codegenerated

- src/generated/apiComponents.ts
- src/generated/apiRequestBodies.ts
- src/generated/apiSchemas.ts
> chore: update api generated code

- src/components/elements/Inputs/DataTable/RHFWorkdaysTable.tsx
- src/constants/options/indigeneity.ts
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
[Task Link](https://gfw.atlassian.net/browse/TM-402)
> feat: TM-402 add new indigeneity dropdown to workdays table

- src/pages/index.page.tsx
Merging learn more translation to staging
> [TM-568] Translate the "learn more" link.

- src/admin/apiProvider/utils/entryFormat.ts
- src/components/extensive/WizardForm/index.tsx
- src/helpers/customForms.ts
[Task Link](https://gfw.atlassian.net/browse/TM-541)
> Draft: Tm 541/saving issues

- src/pages/applications/request-more-information/[id].page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-206)
> feat: TM-206 add download application button

- src/helpers/customForms.ts
[Task Link](https://gfw.atlassian.net/browse/TM-588)
> hotfix: TM-588 check if parsed value exists before assigning it

- src/components/elements/Cards/FundingCard/FundingCard.tsx
[task link](https://gfw.atlassian.net/browse/TM-579)
> fix: TM-579 Blue apply button can stack underneath

- src/pages/form/[id]/pitch-select.page.tsx
[task link](https://gfw.atlassian.net/browse/TM-549)
> feat: TM-549 quotation marks deleted

- src/components/elements/Cards/FundingCard/FundingCard.tsx
- src/pages/applications/request-more-information/[id].page.tsx
[task link](https://gfw.atlassian.net/browse/TM-579)
> Tm 579 mobile view of applications

- src/pages/form/[id]/pitch-select.page.tsx
[task link ](https://gfw.atlassian.net/browse/TM-549)
> Tm 549 edit copy on pitch selection screen

- src/components/elements/Cards/FundingCard/FundingCard.tsx
- src/helpers/customForms.ts
[task link](https://gfw.atlassian.net/browse/TM-418)
> Tm 418 not able to add tree species

- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/QuickActions.tsx
[TM-409](https://gfw.atlassian.net/browse/TM-409) add download shapefile button for sites in admin panel
> feat: TM-409 add download shapefile button for admin

- src/pages/reports/project-report/tabs/ReportData.tsx
[task link](https://gfw.atlassian.net/browse/TM-436)
> feat: TM-436 add tree species grown in nurseries in frontend PD view

- src/components/elements/ServerSideTable/ServerSideTable.tsx
- src/components/extensive/Pagination/index.tsx
- src/components/extensive/Tables/TreeSpeciesTable.tsx
[task link](https://gfw.atlassian.net/browse/TM-436)
> fix: TM-436 toggle hidden page

- src/admin/modules/form/components/CopyFormToOtherEnv.tsx
https://gfw.atlassian.net/browse/TM-583
> fix: TM-583 remove framework when cloning to other env

- src/admin/components/ResourceTabs/ChangeRequestsTab/ChangeRequestsTab.tsx
- src/admin/components/ResourceTabs/ChangeRequestsTab/MoreInformationModal.tsx
- src/components/extensive/ActionTracker/ActionTrackerCard.tsx
- src/components/extensive/ActionTracker/cards/ProjectsCard.tsx
- src/components/extensive/ActionTracker/cards/ReportsCard.tsx
- src/constants/options/status.ts
- src/generated/apiComponents.ts
- src/pages/project/[uuid]/components/StatusBar/EntityStatusBar.tsx
- src/pages/project/[uuid]/components/StatusBar/UpdateRequestStatusBar.tsx
https://gfw.atlassian.net/browse/TM-686
The FE code is mainly just removing support for the "rejected" status on UpdateRequests.
BE PR: https://github.com/wri/wri-terramatch-api/pull/49
> [TM-686] Remove rejected status for update requests.

- src/pages/entity/[entityName]/edit/[uuid]/index.page.tsx
- src/pages/project/[uuid]/components/StatusBar/index.tsx
https://gfw.atlassian.net/browse/TM-684
BE PR: https://github.com/wri/wri-terramatch-api/pull/52
> [TM-684] Retain the "more information requested" banner when a draft update request is in progress.

- src/admin/components/ResourceTabs/ChangeRequestsTab/ChangeRequestsTab.tsx
https://gfw.atlassian.net/browse/TM-570
> [TM-570] When there is an update request awaiting approval, add an icon to the report tab.

- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/QuickActions.tsx
https://gfw.atlassian.net/jira/software/c/projects/TM/issues/TM-679
> TM-679 change export format from json to geojson

- src/pages/project/[uuid]/reporting-task/[reportingTaskUUID].page.tsx
https://gfw.atlassian.net/browse/TM-699
> [TM-699] Show a status bar on the reporting task page.

- src/components/extensive/Tables/CompletedReportsTable.tsx
https://gfw.atlassian.net/browse/TM-701
> [TM-701] Allow report titles to wrap.

- src/admin/components/ResourceTabs/ChangeRequestsTab/ChangeRequestsTab.tsx
- src/admin/components/ResourceTabs/InformationTab/components/NurseryInformationAside/NurseryOverview.tsx
- src/admin/components/ResourceTabs/InformationTab/components/ProjectInformationAside/ProjectOverview.tsx
- src/admin/components/ResourceTabs/InformationTab/components/ReportInformationAside/ReportOverview.tsx
- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/SiteOverview.tsx
- src/components/elements/Inputs/Dropdown/Dropdown.tsx
- src/constants/options/status.ts
- src/generated/apiComponents.ts
- src/pages/reports/project-report/tabs/UploadedFiles.tsx
https://gfw.atlassian.net/browse/TM-700
BE PR: https://github.com/wri/wri-terramatch-api/pull/64
> [TM-700] Better support for change request statuses in the admin site.

- src/components/extensive/Tables/ReportingTasksTable.tsx
- src/pages/project/[uuid]/reporting-task/[reportingTaskUUID].page.tsx
https://gfw.atlassian.net/browse/TM-713
> [TM-713] Improve the UI for PDs viewing a Task with needs-more-information reports.

- src/admin/components/EntityEdit/EntityEdit.tsx
https://gfw.atlassian.net/browse/TM-708
> [TM-708] Admins need to fold in update request data as well.

- src/admin/components/ResourceTabs/InformationTab/index.tsx
https://gfw.atlassian.net/browse/TM-716
> [TM-716] Clear indication of the nothing to report flag.

- src/pages/project/[uuid]/reporting-task/[reportingTaskUUID].page.tsx
https://gfw.atlassian.net/browse/TM-719
> [TM-719] Use the status flag instead of completion % to indicate the state of the report.

- src/admin/components/ResourceTabs/InformationTab/components/ReportInformationAside/ReportOverview.tsx
https://gfw.atlassian.net/browse/TM-717
> [TM-717] Disable the action buttons on reports when there's an active update request.

- src/admin/apiProvider/dataProviders/index.ts
- src/admin/apiProvider/dataProviders/taskDataProvider.ts
- src/admin/components/App.tsx
- src/admin/components/ResourceTabs/InformationTab/components/ReportInformationAside/QuickActions.tsx
- src/admin/modules/index.tsx
- src/admin/modules/tasks/components/TaskShow.tsx
- src/admin/modules/tasks/components/TasksList.tsx
- src/constants/options/status.ts
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
https://gfw.atlassian.net/browse/TM-563
BE: https://github.com/wri/wri-terramatch-api/pull/68
> [TM-563] Support tasks in the Admin UI

- src/components/extensive/Tables/ReportingTasksTable.tsx
https://gfw.atlassian.net/browse/TM-686
> [TM-686] Display correct statuses for reporting tasks.

- src/components/extensive/Tables/ReportingTasksTable.tsx
https://gfw.atlassian.net/browse/TM-732
> [TM-732] Report tables show blue for awaiting approval.

- src/components/extensive/Tables/ReportingTasksTable.tsx
- src/pages/project/[uuid]/reporting-task/[reportingTaskUUID].page.tsx
https://gfw.atlassian.net/browse/TM-712
BE: https://github.com/wri/wri-terramatch-api/pull/76
> [TM-712] Take the change request status into account when calculating the completion status

- src/assets/icons/check-progressbar.svg
- src/assets/icons/search.svg
- src/components/elements/ProgressBar/StepProgressbar/StepProgressbar.stories.tsx
- src/components/elements/ProgressBar/StepProgressbar/StepProgressbar.tsx
- src/components/extensive/Icon/Icon.tsx
> add progressbar

- src/components/elements/Menu/Menu.stories.tsx
- src/components/elements/Menu/Menu.tsx
- src/components/elements/Menu/MenuVariant.ts
- src/components/elements/MenuItem/MenuItem.stories.tsx
- src/components/elements/MenuItem/MenuItem.tsx
- src/components/elements/MenuItem/MenuItemVariant.ts
- Adding Menu component
- Adding Menu Item component
> Design menu

- src/components/extensive/Modal/ModalWithClose.stories.tsx
- src/components/extensive/Modal/ModalWithClose.tsx
- src/components/extensive/Modal/ModalWithLogo.stories.tsx
- src/components/extensive/Modal/ModalWithLogo.tsx
- Add modal with Header
- Add modal with Close
> design: add modal variant

- src/admin/components/ResourceTabs/InformationTab/index.tsx
- src/admin/components/Tables/SeedingsTable.tsx
https://gfw.atlassian.net/browse/TM-751
> [TM-571] Display a seedings table on site and site report pages.

- src/types/common.ts
> fix: upload .shp and .prj files

- package.json
- sentry.client.config.ts
- yarn.lock
https://gfw.atlassian.net/browse/TM-791
> [TM-792] Update frontend Sentry configuration.

- src/admin/components/ResourceTabs/AuditLogTab/AuditLogTab.tsx
https://gfw.atlassian.net/browse/TM-822
> [TM-822] Show line breaks in the audit log.

- package.json
- src/components/elements/Map-mapbox/hooks/useConvertShapefileToGeoJson.ts
- yarn.lock
https://gfw.atlassian.net/browse/TM-818
> TM-818 fix: upload zipped shapefiles

- src/components/elements/Inputs/TreeSpeciesInput/RHFTreeSpeciesInput.tsx
https://gfw.atlassian.net/browse/TM-890
> [HOTFIX] [TM-890] Include the collection when creating tree species.

- src/components/elements/Cards/ProjectCard/ProjectCard.tsx
- src/pages/project/[uuid]/index.page.tsx
- src/pages/reports/nursery-report/[uuid].page.tsx
- src/pages/reports/project-report/[uuid].tsx
- src/pages/reports/site-report/[uuid].page.tsx
- src/pages/site/[uuid]/index.page.tsx
https://gfw.atlassian.net/browse/TM-685
> TM-685 fix: change label from Terrafund to TerraFund

- src/components/elements/Menu/Menu.tsx
- src/components/elements/MenuItem/MenuItem.tsx
- src/components/extensive/PageElements/Card/UserRoleCard.tsx
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
- src/pages/auth/create-account/MockedData.ts
- src/pages/auth/create-account/index.page.tsx
- src/pages/auth/signup/index.page.tsx
> feat: add signup functionality to change login view

- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/components/elements/Map-mapbox/MapService.js
- src/components/elements/Map-mapbox/MapSites.tsx
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
add new map and zoom to site in map
> add new map and fly to geom

- src/components/elements/Map-mapbox/MapControls/StyleControl.tsx
- src/components/elements/Map-mapbox/MapControls/ZoomControl.tsx
- src/components/elements/Map-mapbox/MapService.js
- src/components/elements/Map-mapbox/MapSites.tsx
- src/context/mapSites.provider.tsx
add map provider and use context for polygon review
> add map provider and use context for polygon review

- src/admin/modules/user/components/UserEdit.tsx
- src/admin/modules/user/const.ts
add role options and disabled role select
> feat: add role options

- src/admin/components/ResourceTabs/PolygonReviewTab/components/Polygons.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/components/elements/Map-mapbox/MapControls/FilterLayer.tsx
- src/components/elements/Map-mapbox/MapControls/StyleControl.tsx
- src/components/elements/Map-mapbox/MapSites.tsx
add fitbounds, show options over map  and fix status
> add fitbounds, show options over map  and fix status

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/AttributeInformation.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/Polygons.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/components/elements/Map-mapbox/MapService.js
- src/components/elements/Map-mapbox/MapSites.tsx
- src/context/sitePolygon.provider.tsx
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
feat: add newstyles for site map
> feat: add newstyles for site map

- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
feat: add functionality for download sites polygons
> feat: add functionality for download sites polygons

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonReviewAside/index.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/Polygons.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/components/elements/Map-mapbox/MapService.js
- src/components/elements/Map-mapbox/MapSites.tsx
- src/components/elements/TooltipMap/TooltipMap.tsx
feat: add functionality over tooltip in map
> feat: add functionality over tooltip in map

- src/admin/modules/user/const.ts
- src/generated/apiSchemas.ts
- src/pages/auth/create-account/MockedData.ts
- src/pages/auth/create-account/index.page.tsx
- src/pages/auth/signup/components/SignupForm.tsx
- src/pages/auth/signup/index.page.tsx
Change role id by primary role
> Change role id by primary role

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/AttributeInformation.tsx
- src/components/elements/TooltipMap/TooltipMap.tsx
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
add tooltip and save polygon data
> add tooltip and save polygon data

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/AttributeInformation.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/Polygons.tsx
- src/components/elements/Map-mapbox/MapService.js
- src/components/elements/Map-mapbox/MapSites.tsx
- src/components/extensive/Modal/ModalWithMap.tsx
- src/generated/apiComponents.ts
fix: add geoms in support requested
> fix: add geoms in support requested

- src/components/extensive/Modal/ModalWithMap.tsx
fix issue with undefined value
> fix issue with undefined value

- src/admin/apiProvider/utils/entryFormat.ts
Found during testing on staging for https://gfw.atlassian.net/browse/TM-836
> [TM-836] Replace all newlines with HTML breaks in the info tab form answer display.

- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
feat: add new function to download site polygon as featureCollection
> feat: add new function to download site polygon as featureCollection

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/AttributeInformation.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/Polygons.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/components/elements/Map-mapbox/Map.tsx
- src/context/sitePolygon.provider.tsx
recall data on delete polygon to reload
> add function to provider to refetch data of sites

- src/components/elements/Inputs/ConditionalInput/ConditionalInput.tsx
- src/components/elements/Inputs/DataTable/RHFWorkdaysTable.tsx
change register and unregister to conditional input
> fix: change register and unregister to conditional input

- src/components/elements/Inputs/FileInput/RHFFileInput.tsx
- src/components/extensive/WizardForm/FieldMapper.tsx
- src/utils/errors.ts
[task](https://gfw.atlassian.net/browse/TM-893)
> add limit message to files

- src/components/elements/Inputs/FileInput/RHFFileInput.tsx
- src/components/elements/Inputs/Input/Input.tsx
- src/components/elements/Inputs/SelectImage/RHFSelectImage.tsx
- src/components/elements/Inputs/textArea/TextArea.tsx
- src/components/extensive/WizardForm/FormStep.tsx
- src/components/extensive/WizardForm/index.tsx
add formHook trigger and reset to fields
> [TM-831] fix: add formHook trigger and reset to fields

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/AttributeInformation.tsx
- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/Map-mapbox/MapService.js
> fix: basemap change

- src/components/elements/Inputs/ConditionalInput/ConditionalInput.tsx
- src/components/elements/Inputs/DataTable/DataTable.tsx
- src/components/elements/Inputs/DataTable/RHFDisturbanceTable.tsx
- src/components/elements/Inputs/Dropdown/RHFDropdown.tsx
- src/components/extensive/Tables/DisturbancesTable.tsx
- src/components/extensive/Tables/TreeSpeciesTable.tsx
- src/components/extensive/WizardForm/FormStep.tsx
- src/components/extensive/WizardForm/index.tsx
- src/hooks/useProcessRecordData.ts
[task link](https://gfw.atlassian.net/browse/TM-892)
> Tm 892 conditional questions

- src/hooks/useProcessRecordData.ts
[task link](https://gfw.atlassian.net/browse/TM-917)
> fix: view table tree species to nursery project

- src/admin/apiProvider/utils/user.ts
- src/admin/modules/user/const.ts
https://gfw.atlassian.net/browse/TM-904
[BE PR](https://github.com/wri/wri-terramatch-api/pull/197)
> [TM-904] Allow the creation of HBF admins.

- src/components/elements/Inputs/FileInput/RHFFileInput.tsx
- src/components/elements/Inputs/Input/Input.tsx
- src/components/elements/Inputs/SelectImage/RHFSelectImage.tsx
- src/components/elements/Inputs/textArea/TextArea.tsx
- src/components/extensive/WizardForm/index.tsx
> Code cleanup

- src/components/elements/Inputs/Map/RHFMap.tsx
- src/components/elements/Map-mapbox/MapControls/FeatureDetailCard.tsx
- src/components/elements/Map-mapbox/MapLayers/ShapePropertiesModal.tsx
- src/components/elements/Map-mapbox/components/ControlGroup.tsx
https://gfw.atlassian.net/browse/TM-675
[BE PR](https://github.com/wri/wri-terramatch-api/pull/204)
> [TM-675] Display the `ppc_external_id` field on polygon editing UI in Site forms.

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/PolygonValidation.tsx
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
feat: add check polygon functionality
> add check polygon functionality

- src/admin/components/ResourceTabs/AuditLogTab/AuditLogSiteTab.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogPolygonStatus.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogPolygonStatusSide.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogProjectStatus.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogProjectStatusSide.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogSiteStatus.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogSiteStatusSide.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/ComentarySection/ComentarySection.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonStatus/StatusDisplay .tsx
- src/components/elements/Comentary/Comentary.tsx
- src/components/elements/ComentaryBox/ComentaryBox.tsx
- src/components/elements/Inputs/textArea/TextArea.tsx
- src/components/extensive/Modal/ModalConfirm.tsx
- src/generated/apiSchemas.ts
Add message change request and filter to audit log functionality
> add polygon status functionality

- src/admin/components/ResourceTabs/InformationTab/components/ReportInformationAside/HighLevelMetrics.tsx
https://gfw.atlassian.net/browse/TM-931
> [TM-931] Include high level workday totals metrics on project and site reports

- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/SiteOverview.tsx
- src/pages/site/[uuid]/index.page.tsx
https://gfw.atlassian.net/browse/TM-674
> [TM-674] Display PPC external Site IDs on admin and PD side

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/PolygonValidation.tsx
show correct number in validations
> show correct number in validations

- src/components/elements/ComentaryBox/ComentaryBox.tsx
Add validation to charge files
> add validation to files

- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/Map-mapbox/MapControls/CheckPolygonControl.tsx
- src/generated/apiComponents.ts
- src/generated/apiRequestBodies.ts
- src/generated/apiSchemas.ts
add site Polygons validation functionality
> add site Polygons validation functionality

- src/admin/components/ResourceTabs/PolygonReviewTab/components/Polygons.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
feat: add edit polygon, zoom to and dlete functionality to table
> feat: add edit polygon, zoom to and dlete functionality to table

- src/components/elements/Cards/GoalProgressCard/GoalProgressCard.tsx
- src/components/elements/Cards/GoalProgressCard/GoalProgressCardItem.tsx
change format to values in project and site overview section
> add format to values in project and site overview section

- src/admin/components/ResourceTabs/InformationTab/index.tsx
[task](https://gfw.atlassian.net/browse/TM-755)
> Tm 755 add total fields to site reports ppc in admin view

- src/hooks/useFramework.ts
- src/pages/project/[uuid]/index.page.tsx
[task](https://gfw.atlassian.net/browse/TM-936)
> feat: TM-936 change logic to useFramework

- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogPolygonStatus.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogPolygonStatusSide.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogProjectStatusSide.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogSiteStatusSide.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonStatus/StatusDisplay .tsx
- src/components/elements/ComentaryBox/ComentaryBox.tsx
fixes issues, data types and call mutations
> fixes issues, data types and call mutations

- src/admin/apiProvider/utils/entryFormat.ts
- src/admin/components/ResourceTabs/AuditLogTab/AuditLogSiteTab.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogPolygonStatus.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogPolygonStatusSide.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogProjectStatus.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogProjectStatusSide.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogSiteStatus.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogSiteStatusSide.tsx
Add title to change request and change time zone
> feat: add title to request and change timeZone to date

- src/components/elements/Inputs/Map/RHFMap.tsx
https://gfw.atlassian.net/browse/TM-921
> [HOTFIX] [TM-921] Avoid polygon validations for project map inputs.

- src/admin/components/ResourceTabs/AuditLogTab/AuditLogTab.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonStatus/StatusDisplay .tsx
- src/components/elements/Inputs/Checkbox/Checkbox.tsx
- src/generated/apiComponents.ts
add request project polygons and selected polygon
> add request project polygons

- src/components/elements/Inputs/Input/Input.tsx
- src/pages/auth/signup/components/SignupForm.tsx
- src/pages/auth/signup/index.page.tsx
> fix: signup issues

- src/admin/components/ResourceTabs/AuditLogTab/AuditLogSiteTab.tsx
- src/admin/components/ResourceTabs/AuditLogTab/AuditLogTab.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogPolygonStatus.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogPolygonStatusSide.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogProjectStatus.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogSiteStatus.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/ComentarySection/ComentarySection.tsx
- src/components/elements/ComentaryBox/ComentaryBox.tsx
- src/generated/apiSchemas.ts
> remove useGetAttachment and use attachment relationship

- src/components/elements/Commentary/Commentary.stories.tsx
- src/components/elements/Commentary/Commentary.tsx
- src/components/elements/Status/Status.tsx
- src/components/extensive/Carousel/Carousel.tsx
- src/components/extensive/Modal/Modal.tsx
- src/components/extensive/Modal/ModalAdd.stories.tsx
- src/components/extensive/Modal/ModalAdd.tsx
- src/components/extensive/Modal/ModalApprove.tsx
- src/components/extensive/Modal/ModalConfirm.stories.tsx
- src/components/extensive/Modal/ModalConfirm.tsx
- src/components/extensive/Modal/ModalContent/MockedData.ts
- src/components/extensive/Modal/ModalImageGallelry.stories.tsx
- src/components/extensive/Modal/ModalImageGallery.tsx
- src/components/extensive/Modal/ModalRoot.tsx
- src/components/extensive/Modal/ModalSubmit.stories.tsx
- src/components/extensive/Modal/ModalSubmit.tsx
- src/components/extensive/Modal/ModalWithClose.stories.tsx
- src/components/extensive/Modal/ModalWithClose.tsx
- src/components/extensive/Modal/ModalWithLogo.stories.tsx
- src/components/extensive/Modal/ModalWithLogo.tsx
- src/components/extensive/Modal/ModalWithMap.tsx
This PR makes changes to the styles of the Modal component and adds new scaffolded modal types (map, carousel, lists) that can be used in future pages.
Modal Styles Update:
- Improvements and adjustments to the existing styles for better appearance and usability.
New Scaffolded Modal Types:
- Map: Modal with a basic structure to include a map.
- Carousel: Modal with a basic structure to include a carousel of images or content.
- Lists: Modal with a basic structure to display lists.
> Feat/Edit Modal Component and Add Modal Types

- src/admin/components/ResourceTabs/InformationTab/components/ProjectInformationAside/HighLevelMetrics.tsx
- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/HighLevelMetrics.tsx
https://gfw.atlassian.net/browse/TM-938
[BE PR](https://github.com/wri/wri-terramatch-api/pull/241)
> [TM-938] Include the self-reported numbers in the project/site high level metrics

- src/pages/nursery/[uuid]/index.page.tsx
- src/pages/project/[uuid]/index.page.tsx
- src/pages/site/[uuid]/index.page.tsx
[task](https://gfw.atlassian.net/browse/TM-936)
> feat: TM-936 change HBF -> Harit Bharat Fund

- src/pages/project/[uuid]/tabs/Overview.tsx
- src/pages/site/[uuid]/tabs/Overview.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-938)
> revert: change workdays_count to self_reported_workdays_count

- src/admin/components/Actions/ListActionsCreate.tsx
- src/admin/components/Actions/ShowActions.tsx
- src/admin/components/App.tsx
- src/admin/components/AppLayout.tsx
- src/admin/components/AppMenu.tsx
- src/admin/components/ResourceTabs/ChangeRequestsTab/useFormChanges.ts
- src/admin/components/ResourceTabs/InformationTab/components/InformationTabRow.tsx
- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/HighLevelMetrics.tsx
- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/QuickActions.tsx
- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/SiteOverview.tsx
- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/index.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/ComentarySection/ComentarySection.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/PolygonValidation.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/VersionHistory.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonStatus/StatusDisplay .tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/SitePolygonStatus/SitePolygonStatus.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/StatusLeyend.tsx
- src/admin/components/ShowTitle/index.tsx
- src/admin/components/Tables/TreeSpeciesTable.tsx
- src/components/elements/CommentaryBox/CommentaryBox.tsx
- src/components/extensive/Icon/Icon.tsx
This PR focuses on editing the design in the admin panel, including  the addition of new elements for improved functionality and aesthetics.
New Design Elements:
Added new design elements to the admin panel to support future features and functionalities.
> Feat/ Add style to new admin view 

- src/generated/apiComponents.ts
- src/hooks/useAuditLogActions.ts
Add criteria validations to polygon status
> add criteria validations to polygons

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
- src/hooks/useAuditLogActions.ts
- src/hooks/useLoadEntityList.ts
> change uuid -> poly_id

- src/components/elements/CommentaryBox/__snapshots__/CommentaryBox.stories.storyshot
- src/components/elements/Inputs/textArea/TextArea.hooks.ts
- src/components/elements/Inputs/textArea/__snapshots__/TextArea.stories.storyshot
- src/components/extensive/Modal/__snapshots__/ModalWithLogo.stories.storyshot
- src/hooks/useGetCustomFormSteps/__snapshots__/useGetCustomFormSteps.stories.storyshot
issue with textarea not capturing values or allowing input
> Fix: issue with textarea not capturing values or allowing input

- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
call bbox bounds after a upload of file
> call bbox bounds on upload data

- src/admin/components/ResourceTabs/InformationTab/components/ProjectInformationAside/HighLevelMetrics.tsx
- src/admin/components/ResourceTabs/InformationTab/components/ReportInformationAside/HighLevelMetrics.tsx
- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/HighLevelMetrics.tsx
https://gfw.atlassian.net/browse/TM-911
This is the second time this work has gone into review; this time it's getting merged into the new release branch.
[BE PR](https://github.com/wri/wri-terramatch-api/pull/266)
> [TM-911] Display seeding counts on project, site and their report admin pages.

- src/admin/components/ResourceTabs/InformationTab/components/ProjectInformationAside/HighLevelMetrics.tsx
- src/admin/components/ResourceTabs/InformationTab/components/ReportInformationAside/HighLevelMetrics.tsx
- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/HighLevelMetrics.tsx
- src/components/elements/ServerSideTable/ServerSideTable.tsx
- src/components/extensive/Pagination/index.tsx
- src/components/extensive/Tables/TreeSpeciesTable.tsx
- src/hooks/useProcessRecordData.ts
- src/pages/reports/site-report/[uuid].page.tsx
[Jira Release](https://gfw.atlassian.net/projects/TM/versions/10207/tab/release-report-all-issues)
[BE PR](https://github.com/wri/wri-terramatch-api/pull/283)
> [RELEASE] Incredible Iroko

- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/Map-mapbox/MapControls/EmptyStateDisplay.tsx
- src/pages/project/[uuid]/components/OverviewMapArea.tsx
> [TM-872] site 0 state display

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/AttributeInformation.tsx
- src/components/elements/MapPolygonPanel/AttributeInformation.tsx
https://gfw.atlassian.net/browse/TM-850
> [TM-850] update values for attributes options

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
https://gfw.atlassian.net/browse/TM-847
> [TM-847] add mutate and update function for validation

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/AttributeInformation.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/components/elements/MapPolygonPanel/AttributeInformation.tsx
https://gfw.atlassian.net/browse/TM-850
> [TM-850] change attribute values

- src/components/elements/Inputs/AutoCompleteInput/__snapshots__/AutoCompleteInput.stories.storyshot
- src/components/elements/Inputs/Input/Input.tsx
- src/components/elements/Inputs/Input/__snapshots__/Input.stories.storyshot
Removed handleChange as form updates are handled by formHook.
[Task Link](https://gfw.atlassian.net/browse/TM-995)
> [TM-995] fix: remove handle change function

- src/admin/components/ResourceTabs/GalleryTab/GalleryImageItem.tsx
- src/components/elements/ImageGallery/ImageGallery.tsx
- src/components/elements/ImageGallery/ImageGalleryItem.tsx
- src/components/elements/ImageWithChildren/ImageWithChildren.tsx
- src/components/elements/ImageWithPlaceholder/ImageWithPlaceholder.tsx
- src/components/extensive/Pagination/PerPageSelector.tsx
- src/components/extensive/Pagination/index.tsx
Please check if your PR fulfills the following requirements:
Please check the type of change your PR introduces:
Issue Number: N/A
-
-
-
> design-fix-gallery

- src/pages/project/[uuid]/tabs/Overview.tsx
https://gfw.atlassian.net/browse/TM-991
> [TM-991] change label to Add New Site

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/PolygonReviewButtons.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
https://gfw.atlassian.net/browse/TM-990
> [TM-990] site status wrap for smalll screens

- src/admin/components/Dialogs/InviteMonitoringPartnerDialog.tsx
- src/pages/project/[uuid]/components/InviteMonitoringPartnerModal.tsx
https://gfw.atlassian.net/browse/TM-915
[BE PR](https://github.com/wri/wri-terramatch-api/pull/303)
> [TM-915] Send new users to the password reset page instead.

- src/components/elements/TooltipMap/TooltipMap.tsx
https://gfw.atlassian.net/browse/TM-1000
> [TM-1000] add site name in map tooltip

- src/assets/icons/ic-error-panel.svg
- src/components/elements/MapPolygonPanel/ChecklistInformation.tsx
- src/components/elements/MapPolygonPanel/MapMenuPanelItem.tsx
- src/components/elements/MapSidePanel/MapSidePanel.tsx
- src/components/extensive/Icon/Icon.tsx
Fix icon size for checklist and download geojson with polygon name
> [TM-1002] change size of icon X in checklist and download with polyname

- next.config.js
Small lint issue that I come across in next config.
> fix small lint issue

- src/components/elements/Map-mapbox/MapControls/CheckPolygonControl.tsx
- src/components/elements/MapPolygonPanel/MapPolygonCheckPanel.tsx
https://gfw.atlassian.net/browse/TM-1002
> [TM-1002] remove unused code

- src/pages/project/[uuid]/tabs/Details.tsx
A null value that I found while testing projects.
> hotfix: null coalescing on restoration_strategy project detail

- src/pages/auth/login/components/LoginForm.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1024)
> [TM-1024] changetext New to TerraMatch’s Dashboards -> New to TerraMatch

- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/Map-mapbox/utils.ts
- src/constants/layers.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1030)
Small issue where polygon layer ends up on top of media popups layer making it difficult to see.
> [TM-1030] fix problem with popup displaying below polygon

- src/pages/site/[uuid]/tabs/Overview.tsx
> restore text component

- src/admin/components/ResourceTabs/PolygonReviewTab/components/AddDataButton.tsx
- src/components/elements/Map-mapbox/MapControls/CheckPolygonControl.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1035)
> [TM-1035] hiding unused elements

- src/components/elements/Notification/Notification.tsx
- src/pages/site/[uuid]/tabs/Overview.tsx
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1048)
> [TM-1048]  update alert in Submit  Polygons

- src/admin/components/ResourceTabs/PolygonReviewTab/components/Polygons.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/components/elements/Map-mapbox/utils.ts
- src/components/elements/MapPolygonPanel/MapPolygonCheckPanelItem.tsx
- src/pages/site/[uuid]/tabs/Overview.tsx
https://gfw.atlassian.net/browse/TM-1049
> [TM-1049] change file name when downloading

- src/pages/project/[uuid]/tabs/Overview.tsx
- src/pages/site/[uuid]/tabs/Overview.tsx
[Task Link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1051)
> [TM-1051]  add blur in monitoring section

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/Polygons.tsx
- src/components/elements/MapPolygonPanel/MapPolygonCheckPanelItem.tsx
- src/components/elements/TooltipMap/TooltipMap.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1043)
> [TM-1043] design hide ui elements

- src/admin/components/ResourceTabs/PolygonReviewTab/components/AddDataButton.tsx
- src/components/elements/Map-mapbox/MapControls/CheckPolygonControl.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1035)
> [TM-1035] Hide design elements: Add Images and text above 'check polygons'

- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/Map-mapbox/MapControls/CheckIndividualPolygonControl.tsx
- src/components/elements/Map-mapbox/MapControls/CheckPolygonControl.tsx
- src/components/elements/Map-mapbox/components/OverviewMapArea.tsx
https://gfw.atlassian.net/browse/TM-1046
> [TM-1046] change check polygon text and add condition to show it

- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/TooltipMap/TooltipMap.tsx
https://gfw.atlassian.net/browse/TM-1045
> [TM-1045] assign draft on create

- src/pages/site/[uuid]/tabs/Overview.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1003)
Small issue detected during UAT
> [TM-1003] fix submit polygon status

- src/components/elements/Map-mapbox/MapControls/CheckPolygonControl.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1059)
Update of status verification for polygons on dropdown based on criteria
> [TM-1059] change status verification for polygons on dropdown

- src/components/elements/Map-mapbox/MapControls/CheckIndividualPolygonControl.tsx
- src/components/elements/Map-mapbox/MapControls/CheckPolygonControl.tsx
https://gfw.atlassian.net/browse/TM-1047
> [TM-1047] add alert for check polygons

- src/styles/globals.css
[Task Link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1061)
> [TM-1061] Submit Polygons (Design): fix font-size of polygon name

- src/pages/auth/login/components/LoginForm.tsx
- src/pages/auth/signup/components/SignupForm.tsx
- src/pages/auth/signup/index.page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1024)
> [TM-1024] sign in page issue

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
https://gfw.atlassian.net/browse/TM-1055
> [TM-1055] add condition for validation parsing

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonStatus/StatusDisplay.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1052)
> [TM-1052] change ? -> . to polygon text

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/AttributeInformation.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/Polygons.tsx
- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/Map-mapbox/MapControls/CheckIndividualPolygonControl.tsx
- src/components/elements/Map-mapbox/components/OverviewMapArea.tsx
- src/components/elements/MapPolygonPanel/AttributeInformation.tsx
- src/components/elements/MapPolygonPanel/hooks/useAlertHook.tsx
- src/context/mapArea.provider.tsx
Add alerts for edit geometry, save geometries in Site and Admin views.
> [TM-1062,1063] alert edit polygon attributes

- src/components/elements/CommentaryBox/CommentaryBox.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1053)
> [TM-1053] attachments do not refresh correctly

- src/components/elements/Map-mapbox/components/OverviewMapArea.tsx
https://gfw.atlassian.net/browse/TM-1002
> [TM-1002] show checkpolygon button on site page only

- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
https://gfw.atlassian.net/browse/TM-1022
Depends on: https://github.com/wri/wri-terramatch-api/pull/316 (backend PR)
> [TM-1022] add source to site attrib table

- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/components/elements/Map-mapbox/MapControls/CheckPolygonControl.tsx
- src/pages/site/[uuid]/tabs/Overview.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1059)
> [TM-1059] reload polygon list after update

- src/pages/site/[uuid]/tabs/Overview.tsx
[Task Link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1076)
> [TM 1076] Update copy and add link to the map view on site profile page

- src/admin/components/ResourceTabs/AuditLogTab/components/AuditLogTable.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-952)
> [TM-952] fix text message

- src/pages/site/[uuid]/tabs/Overview.tsx
[Task Link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1076)
> [TM-1076] Fix/update copy and add link to the map view on site profile page

- src/pages/site/[uuid]/tabs/Overview.tsx
[Task Link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1078)
> [TM-1078] site hide request support

- src/admin/components/Fields/CustomChipField.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/PolygonReviewButtons.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonStatus/StatusDisplay.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/SitePolygonStatus/SitePolygonStatus.tsx
- src/components/elements/Inputs/Dropdown/Dropdown.tsx
- src/components/elements/Inputs/Dropdown/constants/colorMap.ts
- src/components/elements/Map-mapbox/MapControls/SiteStatus.tsx
- src/components/elements/Status/Status.tsx
- src/components/elements/Status/constants/colorBgMap.ts
- src/components/elements/Status/constants/colorTextMap.ts
- src/components/elements/Status/constants/statusMap.ts
- src/components/extensive/Modal/ModalConfirm.stories.tsx
- src/components/extensive/Modal/__snapshots__/ModalConfirm.stories.storyshot
- src/constants/options/__snapshots__/status.test.ts.snap
- src/constants/options/status.ts
- src/utils/statusUtils.ts
[Task Link](https://gfw.atlassian.net/browse/TM-951)
> [TM-951] add dependencies between polygon and site status

- src/admin/components/ResourceTabs/AuditLogTab/AuditLogTab.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogEntityStatusSide.tsx
- src/admin/components/ResourceTabs/AuditLogTab/constants/types.ts
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonStatus/StatusDisplay.tsx
- src/pages/project/[uuid]/tabs/AuditLog.tsx
- src/pages/site/[uuid]/tabs/AuditLog.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1080)
> [TM-1080] remove change status functionality from main entities

- src/admin/components/Fields/CustomChipField.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonStatus/StatusDisplay.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/SitePolygonStatus/SitePolygonStatus.tsx
- src/components/elements/Inputs/Dropdown/Dropdown.tsx
- src/components/elements/Map-mapbox/MapControls/SiteStatus.tsx
- src/components/elements/Status/Status.tsx
- src/components/elements/Status/constants/colorBgMap.ts
- src/components/elements/Status/constants/colorTextMap.ts
- src/components/elements/Status/constants/statusMap.ts
- src/constants/options/__snapshots__/status.test.ts.snap
- src/constants/options/status.ts
- src/utils/statusUtils.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1081)
> [TM-1081] change status text Draft -> Started

- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/SiteOverview.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-951)
> [TM-951 add checkout polygons conditional to approve button

- src/pages/my-projects/index.page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-994)
> [TM-994] feat: add org approval restriction

- src/components/elements/Inputs/InputTable/RHFInputTable.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1016)
> [TM-1016] add validation trigger to onChangeCapture

- src/components/elements/MapPolygonPanel/ChecklistInformation.tsx
[Task Link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1083)
> [TM-1083] Site Profile: Hide the 'Request Support' button until implemented

- src/admin/components/Fields/CustomChipField.tsx
- src/admin/modules/nurseries/components/NurseriesList.tsx
- src/admin/modules/nurseryReports/components/NurseryReportsList.tsx
- src/admin/modules/projectReports/components/ProjectReportsList.tsx
- src/admin/modules/projects/components/ProjectsList.tsx
- src/admin/modules/siteReports/components/SiteReportsList.tsx
- src/admin/modules/sites/components/SitesList.tsx
- tailwind.config.js
[Task Link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1082)
> Tm 1082 keep consistent styling on statuses throughout admin panel

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/AttributeInformation.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/components/elements/Map-mapbox/utils.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1085)
> [TM-1085] site status diagram enable refresh

- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogEntityStatusSide.tsx
- tailwind.config.js
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1084)
> [TM-1084] feat site status diagram style

- src/admin/components/extensive/Modal/ModalApprove.tsx
[TaskLink](https://gfw.atlassian.net/browse/TM-1086)
> [TM-1086] do not allow polygons to be appoved without checking

- src/components/elements/MapPolygonPanel/MapMenuPanelItem.tsx
This feature will be part of the next release.
> [TM-980] hide feature

- src/admin/modules/sites/components/SitesList.tsx
- src/constants/options/status.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1090)
> [TM-1090] add change request field to site index

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
- src/components/elements/MapPolygonPanel/ChecklistInformation.tsx
https://gfw.atlassian.net/browse/TM-1089
> [TM-1089] add coordinate system validation

- src/components/elements/Drawer/Drawer.tsx
- src/components/elements/Drawer/__snapshots__/Drawer.stories.storyshot
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1091)
> [TM-1091] Fix/ polygon checks firefox

- src/components/extensive/EntityMapAndGalleryCard/EntityMapAndGalleryCard.tsx
https://gfw.atlassian.net/browse/TM-1094
Remove the geojson in gallery map
> [TM-1094] Remove geojson in gallery map

- src/pages/project/[uuid]/tabs/GoalsAndProgress.tsx
https://gfw.atlassian.net/browse/TM-1096
> [TM-1096] Use the self reported number on the project goals and progress page

- src/pages/site/[uuid]/tabs/GoalsAndProgress.tsx
- src/pages/site/[uuid]/tabs/Overview.tsx
https://gfw.atlassian.net/browse/TM-1096
> [TM-1096] Use the self reported number on the PD site pages as well.

- src/components/elements/StatusBar/StatusBar.tsx
- src/components/elements/StatusPill/StatusPill.tsx
- src/components/extensive/ActionTracker/ActionTrackerCard.tsx
- src/types/common.ts
[Task link](https://gfw.atlassian.net/browse/TM-1097)
> [TM-1097] status create pill restoration progress

- src/components/elements/StatusBar/StatusBar.tsx
- src/components/elements/StatusPill/StatusPill.tsx
- src/components/extensive/ActionTracker/ActionTrackerCard.tsx
- src/components/extensive/EntityMapAndGalleryCard/EntityMapAndGalleryCard.tsx
- src/pages/project/[uuid]/components/StatusBar/EntityStatusBar.tsx
- src/pages/project/[uuid]/tabs/GoalsAndProgress.tsx
- src/pages/site/[uuid]/tabs/GoalsAndProgress.tsx
- src/pages/site/[uuid]/tabs/Overview.tsx
- src/types/common.ts
https://gfw.atlassian.net/projects/TM/versions/10227/tab/release-report-all-issues
> [RELEASE] Hotfix JJ 2024 07 09

- src/admin/components/Dialogs/StatusChangeModal.tsx
- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/SiteOverview.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1099)
> [TM-1099] add restoration in progress button on site admin

- src/admin/components/Dialogs/StatusChangeModal.tsx
- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/SiteOverview.tsx
https://gfw.atlassian.net/projects/TM/versions/10228/tab/release-report-all-issues
> [RELEASE] Hotfix JJ 2024 07 10

- src/components/elements/Map-mapbox/utils.ts
- src/components/elements/MapPolygonPanel/MapMenuPanelItem.tsx
- src/components/extensive/Modal/ModalWithLogo.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-980)
> [TM-980] enable comment polygon

- src/admin/modules/application/components/ApplicationList.tsx
- src/admin/modules/fundingProgrammes/components/FundingProgrammeList.tsx
- src/admin/modules/nurseries/components/NurseriesList.tsx
- src/admin/modules/nurseryReports/components/NurseryReportsList.tsx
- src/admin/modules/organisations/components/OrganisationsList.tsx
- src/admin/modules/pitch/components/PitchesList.tsx
- src/admin/modules/projectReports/components/ProjectReportsList.tsx
- src/admin/modules/projects/components/ProjectsList.tsx
- src/admin/modules/reportingFramework/components/ReportingFrameworkList.tsx
- src/admin/modules/siteReports/components/SiteReportsList.tsx
- src/admin/modules/sites/components/SitesList.tsx
- src/admin/modules/user/components/UserList.tsx
- src/components/elements/Menu/Menu.tsx
[Task Link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1108)
> [TM-1108] add row clickable to all admin lists

- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/Map-mapbox/utils.ts
- src/components/extensive/WizardForm/FormSummaryRow.tsx
https://gfw.atlassian.net/browse/TM-1079
> [TM-1079] show geojsons in applications and project overview

- src/pages/project/[uuid]/reporting-task/[reportingTaskUUID].page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1116)
> [TM-1116] feat: show pagination to additional reports

- src/pages/project/[uuid]/reporting-task/[reportingTaskUUID].page.tsx
https://gfw.atlassian.net/projects/TM/versions/10229/tab/release-report-all-issues
> [RELEASE] Hotfix JJ 2024 07 12

- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/components/elements/MapPolygonPanel/hooks/useAlertHook.tsx
- src/pages/site/[uuid]/tabs/Overview.tsx
display alert on upload filure
> [TM-1110] Add error message on upload files

- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/admin/modules/validationPolygonFile/components/ValidationPolygonFileShow.tsx
> [TM-973] loadder in upload

- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/SiteOverview.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1120)
> [TM-1120] display site id on admin view

- src/components/elements/Inputs/WorkdaysInput/RHFWorkdaysTable.tsx
- src/components/extensive/WorkdayCollapseGrid/hooks.ts
https://gfw.atlassian.net/browse/TM-1098
[BE PR](https://github.com/wri/wri-terramatch-api/pull/355)
> [TM-1098] Address a data discrepancy in workday demographics that can occur with frequent form updates

- src/pages/entity/[entityName]/create/[frameworkUUID].page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1132?focusedCommentId=29420)
> [TM-1132] fix missing locale usage in report front page

- src/admin/components/App.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1102)
> [TM-1102] redirect to login when no identity

- src/components/elements/CommentaryBox/CommentaryBox.tsx
- src/components/elements/CommentaryBox/__snapshots__/CommentaryBox.stories.storyshot
- src/components/extensive/Modal/ModalConfirm.tsx
- src/components/extensive/Modal/__snapshots__/ModalConfirm.stories.storyshot
- src/components/extensive/Modal/__snapshots__/ModalWithLogo.stories.storyshot
[Task Link](https://gfw.atlassian.net/browse/TM-1121)
> [TM-1121] remove char count

- src/components/elements/Inputs/DataTable/RHFSeedingTable.tsx
https://gfw.atlassian.net/browse/TM-969
> [TM-969] Fix NaN display in admin seedings. 

- src/components/extensive/WorkdayCollapseGrid/WorkdaySection.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1132)
> [TM-1132] missing translations

- src/components/elements/Inputs/FileInput/RHFFileInput.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1151)
> [TM-1151] add cleanErrors to upload files

- src/pages/reports/project-report/tabs/ReportData.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1152)
> [TM-1152] answer showing for challenges faced

- src/admin/components/ResourceTabs/PolygonReviewTab/components/AddDataButton.tsx
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1149)
> [TM-1149] fix/Admin and Site: Change text to "Create Polygon"

- src/hooks/useMessageValidations.ts
https://gfw.atlassian.net/browse/TM-1144
> [TM-1144] update messages

- src/admin/components/ResourceTabs/PolygonReviewTab/components/AddDataButton.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/admin/components/extensive/Modal/ModalIdentified.tsx
- src/components/extensive/Modal/ModalAdd.tsx
- src/components/extensive/Modal/ModalConst.ts
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
- src/pages/site/[uuid]/tabs/Overview.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1136)
> [TM-1136] add upload replacement functionality

- src/admin/components/ResourceTabs/PolygonReviewTab/components/AddDataButton.tsx
[Task Link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1149)
> [TM-1149] Fix Change Text

- src/admin/components/ResourceTabs/PolygonReviewTab/components/Polygons.tsx
- src/components/elements/MapPolygonPanel/MapMenuPanelItem.tsx
- src/components/elements/MapSidePanel/MapSidePanel.tsx
https://gfw.atlassian.net/browse/TM-1144
> [TM-1144] zoom geom when editing

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/AttributeInformation.tsx
- src/components/elements/Map-mapbox/Map.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1130)
> [TM-1130] replacement upload polygons

- src/admin/components/Fields/MapField.tsx
- src/admin/modules/application/components/ApplicationTabs.tsx
- src/components/extensive/WizardForm/FormSummaryRow.tsx
https://gfw.atlassian.net/browse/TM-1111
> [TM-1104] add application map in admin view

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/VersionHistory.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/Polygons.tsx
https://gfw.atlassian.net/browse/TM-1183
fix correct uuid for new version of polygon
> [TM-1183] edit polygon version

- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/MapPolygonPanel/AttributeInformation.tsx
- src/components/elements/MapPolygonPanel/MapEditPolygonPanel.tsx
https://gfw.atlassian.net/browse/TM-1178
> [TM-1179] onsaveattributes to submitted status

- src/components/elements/MapPolygonPanel/AttributeInformation.tsx
https://gfw.atlassian.net/browse/TM-1178
> [TM-1178] Add input validation for pd

- src/pages/organization/[id]/components/edit/OrganizationEditModal.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1191)
> [TM-1191] save button on organization

- src/pages/organization/assign/components/OrganizationAssignForm.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1194)
> [TM-1194] use state for searched term in organization dropdown

- src/pages/site/[uuid]/tabs/Details.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1196)
> [TM-1196] fix details tab from site

- src/pages/site/[uuid]/tabs/Details.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1042)
> [TM-1142] ensure landing pages

- src/pages/site/[uuid]/tabs/Details.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1042)
> [TM-1042] ensure landing pages

- src/pages/site/[uuid]/tabs/Overview.tsx
https://gfw.atlassian.net/browse/TM-1111
> [TM-1111] add error messages in PD view

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/VersionHistory.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/admin/modules/validationPolygonFile/components/ValidationPolygonFileShow.tsx
- src/components/elements/Map-mapbox/MapControls/PolygonHandler.tsx
- src/components/elements/MapPolygonPanel/VersionInformation.tsx
- src/pages/site/[uuid]/tabs/Overview.tsx
https://gfw.atlassian.net/browse/TM-1111
> [TM-1111] Fix spelling

- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/Map-mapbox/components/AdminPopup.tsx
- src/components/elements/Map-mapbox/components/OverviewMapArea.tsx
- src/components/elements/Map-mapbox/utils.ts
- src/components/elements/TooltipMap/TooltipMap.tsx
https://gfw.atlassian.net/browse/TM-1161
> [TM-1161] add option in polygon popup to open edit side panel

- src/admin/modules/sites/components/SitesList.tsx
- src/constants/options/status.ts
https://gfw.atlassian.net/browse/TM-1177
> Feat/[TM 1177] polygon filter

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/VersionHistory.tsx
- src/components/elements/MapPolygonPanel/VersionInformation.tsx
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1176)
> [TM-1176] add version name field to polygon version

- src/admin/apiProvider/dataProviders/userDataProvider.ts
- src/admin/modules/user/components/UserEdit.tsx
- src/admin/modules/user/components/UserList.tsx
- src/admin/modules/user/components/UserShow.tsx
- src/admin/modules/user/components/UserShowAside.tsx
- src/admin/modules/user/const.ts
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
- src/pages/auth/create-account/index.page.tsx
- src/pages/auth/signup/components/SignupForm.tsx
- src/pages/auth/signup/index.page.tsx
- src/pages/organization/[id]/components/team/TeamTabContent.tsx
https://gfw.atlassian.net/browse/TM-1103
[BE PR](https://github.com/wri/wri-terramatch-api/pull/398)
Note that this FE PR won't pass build on Vercel until the BE PR is merged, due to API updates.
> [TM-1103] Update user roles and permissions

- src/admin/components/ResourceTabs/InformationTab/components/ProjectInformationAside/HighLevelMetrics.tsx
- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/HighLevelMetrics.tsx
- src/pages/project/[uuid]/tabs/GoalsAndProgress.tsx
- src/pages/project/[uuid]/tabs/Overview.tsx
- src/pages/site/[uuid]/tabs/GoalsAndProgress.tsx
- src/pages/site/[uuid]/tabs/Overview.tsx
https://gfw.atlassian.net/browse/TM-1155
[BE PR](https://github.com/wri/wri-terramatch-api/pull/403)
> [TM-1155] Display the combined calculation of workday counts.

- src/admin/components/ResourceTabs/ChangeRequestsTab/MoreInformationModal.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1159)
> [TM-1159]: use a new name in form for feedback field

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/PolygonValidation.tsx
- src/components/elements/Map-mapbox/MapControls/CheckPolygonControl.tsx
- src/components/extensive/Modal/ModalConst.ts
- src/components/extensive/Modal/ModalFixOverlaps.tsx
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
https://gfw.atlassian.net/browse/TM-1185
[backend PR](https://github.com/wri/wri-terramatch-api/pull/411)
> [TM-1185] Fix small overlaps

- src/components/elements/Map-mapbox/MapControls/CheckIndividualPolygonControl.tsx
- src/components/elements/MapPolygonPanel/ChecklistInformation.tsx
- src/components/elements/MapPolygonPanel/MapEditPolygonPanel.tsx
- src/context/mapArea.provider.tsx
- src/pages/site/[uuid]/components/SiteArea.tsx
https://gfw.atlassian.net/browse/TM-1185
> [TM-1185] add fix polygon overlaps functionality for single polygons in PD view

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
- src/components/elements/Map-mapbox/MapControls/CheckIndividualPolygonControl.tsx
- src/components/elements/Map-mapbox/MapControls/CheckPolygonControl.tsx
https://gfw.atlassian.net/browse/TM-1185
> [TM-1185] reload site data after fix overlaps polygos

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonItem.tsx
- src/admin/components/extensive/Modal/ModalApprove.tsx
- src/components/elements/MapPolygonPanel/MapMenuPanelItem.tsx
https://gfw.atlassian.net/browse/TM-1174
> [TM-1174] add dropdown to show validation details for valid polygons

- src/pages/reports/project-report/tabs/ReportData.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1157)
> [TM-1157] change attribute names

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/Polygons.tsx
- src/components/elements/Map-mapbox/MapControls/CheckPolygonControl.tsx
https://gfw.atlassian.net/browse/TM-1185
> [TM-1185] refetch validation after fix polygon overlaps

- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/Map-mapbox/utils.ts
https://gfw.atlassian.net/browse/TM-1231
> [TM-1231] remove popup

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonItem.tsx
- src/components/elements/MapPolygonPanel/MapMenuPanelItem.tsx
https://gfw.atlassian.net/browse/TM-1174
> [TM-1174] add text for passed polygons and add transition to icon

- src/components/elements/Map-mapbox/hooks/useMap.ts
Remove drawn polygons on finish draw
> [TM-1231] remove drawn polygons

- src/components/extensive/Modal/ModalAdd.tsx
- src/pages/site/[uuid]/tabs/Overview.tsx
https://gfw.atlassian.net/browse/TM-1260
> [TM-1260] add loader and close modal when uploading new polygons

- src/components/elements/Map-mapbox/components/AdminPopup.tsx
- src/components/elements/TooltipMap/TooltipMap.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1261)
> [TM-1261] add primary uuid params

- src/admin/components/ResourceTabs/InformationTab/components/ReportInformationAside/QuickActions.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1217)
> [TM-1217] add back to entity button on site/nursery reports

- src/admin/components/ResourceTabs/PolygonReviewTab/components/AddDataButton.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/components/elements/Map-mapbox/MapControls/CheckPolygonControl.tsx
- src/components/elements/Map-mapbox/components/OverviewMapArea.tsx
- src/pages/site/[uuid]/tabs/Overview.tsx
https://gfw.atlassian.net/browse/TM-1198
> [TM-1198] clear checkboxes after entering into other modals

- src/hooks/useWorkdayData.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1213)
> [TM-1213] different workday totals displayed

- src/admin/components/ResourceTabs/InformationTab/components/ReportInformationAside/ReportOverview.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1218)
> [TM-1218] add du date field to report overview

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/PolygonValidation.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonItem.tsx
- src/components/elements/Map-mapbox/MapControls/CheckPolygonControl.tsx
- src/components/elements/MapPolygonPanel/ChecklistErrorsInformation.tsx
- src/components/elements/MapPolygonPanel/ChecklistInformation.tsx
- src/components/elements/MapPolygonPanel/MapMenuPanelItem.tsx
- src/components/extensive/Modal/components/CollapsibleRow.tsx
- src/helpers/polygonValidation.ts
https://gfw.atlassian.net/browse/TM-1226
> [TM-1226] warning icon in validation

- src/components/extensive/WizardForm/index.tsx
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1228)
> [TM-1228] Update copy on site establishment: polygon creation banner

- src/admin/components/ResourceTabs/InformationTab/components/ProjectInformationAside/HighLevelMetrics.tsx
- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/HighLevelMetrics.tsx
- src/pages/project/[uuid]/tabs/Overview.tsx
- src/pages/site/[uuid]/tabs/Overview.tsx
https://gfw.atlassian.net/browse/TM-1211
BE PR: https://github.com/wri/wri-terramatch-api/pull/436
> [TM-1211] add hectares under restoration to admin and pd views

- src/components/elements/ImageGallery/ImageGallery.tsx
- src/components/elements/ImageGallery/__snapshots__/ImageGallery.stories.storyshot
[task Link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1237)
> [TM-1237] edit font-weight in text menu

- src/components/elements/Cards/GoalProgressCard/GoalProgressCard.tsx
- src/components/elements/Cards/GoalProgressCard/__snapshots__/GoalProgressCard.stories.storyshot
- src/pages/project/[uuid]/tabs/Overview.tsx
- src/pages/site/[uuid]/tabs/Overview.tsx
https://gfw.atlassian.net/browse/TM-1211?focusedCommentId=31041
> [TM-1211] add progress bar even if value is 0 and remove unused values

- src/components/elements/Cards/GoalProgressCard/GoalProgressCard.tsx
- src/components/elements/Cards/GoalProgressCard/__snapshots__/GoalProgressCard.stories.storyshot
- src/pages/project/[uuid]/tabs/Overview.tsx
https://gfw.atlassian.net/browse/TM-1211
> [TM-1211] progress bar hectars under restoration

- src/admin/modules/nurseryReports/components/NurseryReportsList.tsx
- src/admin/modules/projectReports/components/ProjectReportsList.tsx
- src/admin/modules/siteReports/components/SiteReportsList.tsx
https://gfw.atlassian.net/browse/TM-1190
> [TM-1190] Add organisation filter for reports page

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/AttributeInformation.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1225)
> [TM-1225] Add function close in AttributeInformation

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/AttributeInformation.tsx
- src/pages/project-pitches/components/PitchEditModal.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1288)
> [TM-1288] project pitch edit save

- src/admin/components/ResourceTabs/ChangeRequestsTab/MoreInformationModal.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1267)
> [TM-1267] duplication issue

- src/admin/components/ResourceTabs/InformationTab/components/ProjectInformationAside/HighLevelMetrics.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-437)
> [TM-437] feat: add trees restored field for ppc

- src/admin/components/ResourceTabs/InformationTab/components/ProjectInformationAside/HighLevelMetrics.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-437)
> [TM-437] adding survival rate into trees restored numbers

- src/components/elements/Inputs/LanguageDropdown/LanguagesDropdown.tsx
- src/generated/apiComponents.ts
[Task Link](https://gfw.atlassian.net/browse/TM-578)
> [TM-578] update users locale

- src/admin/components/ResourceTabs/AuditLogTab/components/AuditLogTable.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1284)
> [TM-1284] add reminder sent to action table

- src/admin/components/ResourceTabs/GalleryTab/GalleryTab.tsx
- src/components/elements/ImageGallery/ImageGallery.tsx
- src/components/extensive/EntityMapAndGalleryCard/EntityMapAndGalleryCard.tsx
- src/components/extensive/Pagination/index.tsx
https://gfw.atlassian.net/browse/TM-1237?focusedCommentId=31943
> [TM-1237] image gallery enhancement

- src/components/elements/Inputs/AutoCompleteInput/__snapshots__/AutoCompleteInput.stories.storyshot
- src/components/elements/Inputs/Input/Input.tsx
- src/components/elements/Inputs/Input/__snapshots__/Input.stories.storyshot
[Task Link](https://gfw.atlassian.net/browse/TM-1321)
> [TM-1321] add conditional to onChange

- src/admin/apiProvider/utils/entryFormat.ts
- src/admin/components/ResourceTabs/AuditLogTab/components/AuditLogTable.tsx
- src/components/extensive/WizardForm/index.tsx
- src/pages/entity/[entityName]/edit/[uuid]/EditEntityForm.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1188)
> [TM-1188] update audit log ux

- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/Map-mapbox/MapControls/ViewImageCarousel.tsx
- src/components/extensive/EntityMapAndGalleryCard/EntityMapAndGalleryCard.tsx
[Task Link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1305)
> TM-1305 add scroll and change route to gallery

- src/components/elements/Table/Table.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1339)
> [TM-1339] Add identifier for table rows in react table

- src/components/elements/Table/TableVariants.ts
- src/pages/dashboard/components/ContentOverview.tsx
- src/pages/dashboard/components/HeaderDashboard.tsx
- src/pages/dashboard/country/[id].page.tsx
- src/pages/dashboard/mockedData/dashboard.ts
- src/pages/dashboard/programme/index.page.tsx
[Task Link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1314)
> TM-1314 add country page

- src/components/elements/Map-mapbox/components/MediaPopup.tsx
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1306)
> [TM-1306] change spelling Download

- src/components/elements/Map-mapbox/Map.tsx
- src/pages/dashboard/components/ContentOverview.tsx
> [TM 1343] rebuild map expand

- src/generated/apiComponents.ts
- src/pages/dashboard/components/HeaderDashboard.tsx
https://gfw.atlassian.net/browse/TM-1341
> [TM-1341] add dynamic values in dropdown

- src/components/elements/Table/TableVariants.ts
- src/components/elements/Table/__snapshots__/Table.stories.storyshot
- src/pages/dashboard/components/SecDashboard.tsx
- src/pages/dashboard/index.page.tsx
https://gfw.atlassian.net/browse/TM-1342
> [TM-1342] Top projects

- src/components/elements/Map-mapbox/Map.d.ts
- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/Map-mapbox/components/DashboardPopup.tsx
- src/components/elements/Map-mapbox/utils.ts
- src/constants/layers.ts
- src/pages/dashboard/components/ContentOverview.tsx
- src/pages/dashboard/components/TooltipGridMap.tsx
Add layer visibility for countries in dashboard.
> [TM-1343] add country hover and start popup

- src/admin/components/ResourceTabs/AuditLogTab/components/AuditLogTable.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1057)
> [TM-1057] update audit status action text

- src/constants/dashbordConsts.ts
- src/pages/dashboard/charts/HorizontalStackedBarChart.tsx
- src/pages/dashboard/charts/MultiLineChart.tsx
- src/pages/dashboard/components/SecDashboard.tsx
- src/pages/dashboard/hooks/useDashboardData.ts
- src/pages/dashboard/index.page.tsx
- src/utils/dashboardUtils.ts
https://gfw.atlassian.net/browse/TM-1342
> [TM-1342] add line chart and reorganize code

- src/components/elements/Inputs/Dropdown/Dropdown.tsx
- src/pages/dashboard/components/HeaderDashboard.tsx
https://gfw.atlassian.net/browse/TM-1341
> [TM-1341] change filter option on selecting multiples

- src/components/elements/Inputs/Dropdown/Dropdown.tsx
- src/constants/dashbordConsts.ts
- src/pages/dashboard/charts/MultiLineChart.tsx
- src/pages/dashboard/components/GraphicDashboard.tsx
- src/pages/dashboard/components/SecDashboard.tsx
https://gfw.atlassian.net/browse/TM-1342
> [TM-1342] add relative chart

- src/components/extensive/WorkdayCollapseGrid/WorkdayCollapseGrid.tsx
- src/components/extensive/WorkdayCollapseGrid/WorkdayRow.tsx
- src/components/extensive/WorkdayCollapseGrid/WorkdaySection.tsx
- src/components/extensive/WorkdayCollapseGrid/__snapshots__/WorkdayCollapseGrid.stories.storyshot
- src/components/extensive/WorkdayCollapseGrid/hooks.ts
- src/components/extensive/WorkdayCollapseGrid/types.ts
- src/hooks/useWorkdayData.tsx
https://gfw.atlassian.net/browse/TM-1322
No HBF
HBF
> [TM-1322] Implement Workdays For HBF Reporting

- src/constants/dashbordConsts.ts
- src/pages/dashboard/charts/HorizontalStackedBarChart.tsx
- src/pages/dashboard/charts/MultiLineChart.tsx
- src/utils/dashboardUtils.ts
https://gfw.atlassian.net/browse/TM-1369
> [TM-1369] Jobs created

- src/components/elements/Inputs/FileInput/RHFFileInput.tsx
https://gfw.atlassian.net/browse/TM-1408
> [TM-1408] Restore fileInputProps to FileInput

- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/Map-mapbox/components/DashboardPopup.tsx
- src/components/elements/Map-mapbox/hooks/useMap.ts
- src/components/elements/Map-mapbox/utils.ts
- src/components/extensive/EntityMapAndGalleryCard/EntityMapAndGalleryCard.tsx
- src/components/extensive/WizardForm/FormSummaryRow.tsx
- src/pages/dashboard/components/ContentOverview.tsx
- src/pages/dashboard/hooks/useDashboardData.ts
- src/pages/dashboard/index.page.tsx
add polygons visible in map with popups
> [TM-1343] add polygons visible in dashboard with popups

- src/components/elements/Inputs/FileInput/RHFFileInput.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1408)
> [TM-1408] helper text missing

- src/pages/dashboard/[id].page.tsx
- src/pages/dashboard/components/ContentOverview.tsx
- src/pages/dashboard/components/HeaderDashboard.tsx
- src/pages/dashboard/constants/tooltips.ts
- src/pages/dashboard/hooks/useDashboardData.ts
- src/pages/dashboard/index.page.tsx
- src/pages/dashboard/project/index.page.tsx
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?assignee=712020%3Afdaeb363-5553-48e0-9d3c-0af051b4affb&selectedIssue=TM-1410)
> [TM-1410] dashboard update tooltip definitions and related items

- src/components/elements/Inputs/FileInput/RHFFileInput.tsx
[Jira Release](https://gfw.atlassian.net/projects/TM/versions/10247/tab/release-report-all-issues)
> [RELEASE] Queenly Queenwood Hotfix 2024-10-22

- src/components/elements/Table/TableVariants.ts
- src/components/elements/Table/__snapshots__/Table.stories.storyshot
[Task link](https://gfw.atlassian.net/browse/TM-1313)
> [TM-1313] Z-index position menu in table active project

- src/pages/dashboard/components/DashboardBreadcrumbs.tsx
- src/pages/dashboard/components/HeaderDashboard.tsx
- src/pages/dashboard/hooks/useDashboardData.ts
- src/pages/dashboard/index.page.tsx
- src/pages/dashboard/project-list/index.page.tsx
> [TM-1407] update active project table dynamically

- src/pages/dashboard/components/ObjectiveSec.tsx
- src/pages/dashboard/mockedData/dashboard.ts
> TM-1407 add read more on objective sec

- src/pages/dashboard/components/SecDashboard.tsx
- src/pages/dashboard/hooks/useDashboardData.ts
- src/pages/dashboard/index.page.tsx
https://gfw.atlassian.net/browse/TM-1407?focusedCommentId=33321
> [TM-1407] change from project to organization

- src/admin/components/EntityEdit/EntityEdit.tsx
- src/components/extensive/WorkdayCollapseGrid/hooks.ts
- src/helpers/customForms.ts
https://gfw.atlassian.net/browse/TM-1411
> [TM-1411] Fix entity edit for admins.

- src/pages/_app.tsx
- src/pages/dashboard/DashboardAnalyticsWrapper.tsx
https://gfw.atlassian.net/browse/TM-1419
> [TM-1319] Add HotJar and GoogleAnalytics to the Dashboard

- src/pages/dashboard/index.page.tsx
https://gfw.atlassian.net/browse/TM-1407?focusedCommentId=33321
> [TM-1407] rename table from organization to project

- src/components/elements/Map-mapbox/components/AdminPopup.tsx
- src/components/elements/Map-mapbox/components/DashboardPopup.tsx
- src/components/elements/Map-mapbox/components/MediaPopup.tsx
Fixes the lacking redux context in modals that pop up in their own react root. Reported on slack; no ticket.
> [No Ticket] Provide redux context in modal react roots.

- src/pages/dashboard/components/HeaderDashboard.tsx
https://gfw.atlassian.net/browse/TM-1366
> [TM-1366] change values in landscape options

- src/admin/components/ResourceTabs/InformationTab/index.tsx
- src/admin/modules/nurseries/components/NurseryShow.tsx
- src/admin/modules/nurseryReports/components/NurseryReportShow.tsx
- src/admin/modules/projectReports/components/ProjectReportShow.tsx
- src/admin/modules/projects/components/ProjectShow.tsx
- src/admin/modules/siteReports/components/SiteReportShow.tsx
- src/admin/modules/sites/components/SiteShow.tsx
- src/context/framework.provider.tsx
https://gfw.atlassian.net/browse/TM-1415
> [TM-1415] Provide framework to all tabs on the entity show pages.

- src/admin/components/Dialogs/FrameworkSelectionDialog.tsx
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
- src/utils/network.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1434)
> [TM-1434] unable to download reports admin

- .husky/prepare-commit-msg
- src/admin/modules/user/components/UserEdit.tsx
- src/admin/modules/user/components/UserShow.tsx
- src/admin/modules/user/const.ts
https://gfw.atlassian.net/browse/TM-1384
[PHP PR](https://github.com/wri/wri-terramatch-api/pull/537)
[v3 PR](https://github.com/wri/terramatch-microservices/pull/10)
> [TM-1384] User frameworks

- src/admin/components/Dialogs/FrameworkSelectionDialog.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1434)
> [TM-1434] use correct URL for download file

- src/components/elements/Inputs/DemographicsInput/RHFDemographicsTable.tsx
https://gfw.atlassian.net/browse/TM-1442
> [TM-1442] Pass all extra props to the input wrapper and avoid adding a second title in forms

- src/components/generic/Loading/InlineLoader.tsx
- src/hooks/entity/useGetExportEntityHandler.ts
- src/pages/nursery/[uuid]/components/NurseryHeader.tsx
- src/pages/project/[uuid]/components/ProjectHeader.tsx
- src/pages/project/[uuid]/index.page.tsx
- src/pages/reports/nursery-report/components/NurseryReportHeader.tsx
- src/pages/reports/project-report/components/ProjectReportHeader.tsx
- src/pages/reports/site-report/components/SiteReportHeader.tsx
- src/pages/site/[uuid]/components/SiteHeader.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1417)
> [TM-1417] add loader to export entity

- src/pages/dashboard/index.page.tsx
https://gfw.atlassian.net/browse/TM-1437
> [TM-1437] check if activeCountries is an array

- src/pages/dashboard/index.page.tsx
https://gfw.atlassian.net/browse/TM-1437
> [TM-1437] add correct reference to active country data

- src/components/elements/Inputs/WorkdaysInput/RHFWorkdaysTable.tsx
https://gfw.atlassian.net/projects/TM/versions/10251/tab/release-report-all-issues
> [RELEASE] Rare Redwood Hotfix 2024 11 04

- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
- src/pages/auth/signup/[token].page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1289)
> [TM-1289] update email for new users added as monitoring partners

- src/components/elements/Table/Table.tsx
- src/components/elements/Table/__snapshots__/Table.stories.storyshot
- src/context/dashboard.provider.tsx
- src/pages/dashboard/components/ContentOverview.tsx
- src/pages/dashboard/components/HeaderDashboard.tsx
- src/pages/dashboard/project-list/index.page.tsx
> [TM-1407] redirect on click row in project list

- src/pages/dashboard/charts/CustomLegendJobsCreated.tsx
- src/pages/dashboard/charts/CustomLegendVolunteers.tsx
> [TM-1407] move legends of charts

- src/components/elements/Inputs/Dropdown/Dropdown.tsx
- src/components/extensive/BlurContainer/BlurContainer.tsx
- src/components/generic/Sidebar/Sidebar.tsx
- src/constants/dashboardConsts.ts
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
- src/pages/dashboard/components/GraphicDashboard.tsx
- src/pages/dashboard/components/HeaderDashboard.tsx
- src/pages/dashboard/components/SecDashboard.tsx
- src/pages/dashboard/components/ValueNumberDashboard.tsx
- src/pages/dashboard/hooks/useDashboardData.ts
- src/pages/dashboard/index.page.tsx
- src/pages/dashboard/project-list/index.page.tsx
- src/utils/dashboardUtils.ts
> [TM-1407] Add blur no data

- src/pages/_app.tsx
https://gfw.atlassian.net/browse/TM-1459
> [TM-1459] Fix setting up client side translations.

- src/pages/dashboard/components/ContentOverview.tsx
- src/pages/dashboard/index.page.tsx
> [TM-1343] add values for countr project

- src/pages/_app.tsx
https://gfw.atlassian.net/projects/TM/versions/10252/tab/release-report-all-issues
> [RELEASE] Rare Redwood hotfix 2024 11 07

- src/pages/dashboard/project-list/index.page.tsx
[Task link](https://gfw.atlassian.net/browse/TM-1316)
> [TM-1316] add break in text TerraFund Top 100 in programme table list

- src/pages/dashboard/about-us/index.page.tsx
- src/pages/dashboard/components/TabCarouselAboutUs.tsx
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1375)
> [TM-1375] add href in content about -us

- src/components/elements/Map-mapbox/Map.tsx
- src/components/extensive/BlurContainer/BlurContainer.tsx
- src/components/extensive/PageElements/Card/PageCard.tsx
- src/components/generic/Sidebar/Sidebar.tsx
- src/constants/dashboardConsts.ts
- src/pages/dashboard/[id].page.tsx
- src/pages/dashboard/charts/MultiLineChart.tsx
- src/pages/dashboard/components/ContentOverview.tsx
- src/pages/dashboard/components/HeaderDashboard.tsx
- src/pages/dashboard/components/SecDashboard.tsx
- src/pages/dashboard/hooks/useDashboardData.ts
- src/pages/dashboard/index.page.tsx
- src/pages/dashboard/project/index.page.tsx
- src/utils/dashboardUtils.ts
https://gfw.atlassian.net/browse/TM-1343
> [TM-1343] fixes dashboard

- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/Map-mapbox/components/DashboardPopup.tsx
- src/components/elements/Map-mapbox/utils.ts
- src/pages/dashboard/components/TooltipGridMap.tsx
> [TM-1343] Fix popup issue

- src/pages/dashboard/components/HeaderDashboard.tsx
- src/pages/dashboard/index.page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1313?focusedCommentId=33867)
> [TM-1313] TM-1313 fix flags aspect ratio and graphic text

- src/admin/modules/form/components/FormBuilder/QuestionArrayInput.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1470)
> [TM-1470] add on delete question in questionArrayInput component

- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/Map-mapbox/hooks/useMap.ts
The only token used now is: NEXT_APP_MAPBOX_TOKEN
> [TM-1343] remove token unused

- src/components/elements/Table/Table.tsx
- src/components/elements/Table/TableVariants.ts
- src/components/elements/Table/__snapshots__/Table.stories.storyshot
- src/pages/dashboard/components/ContentOverview.tsx
- src/pages/dashboard/index.page.tsx
- src/styles/extended-utilities.css
[task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?assignee=712020%3Afdaeb363-5553-48e0-9d3c-0af051b4affb&selectedIssue=TM-1314)
> [TM-1314] modifi scroll in table and content

- src/pages/dashboard/components/HeaderDashboard.tsx
- src/utils/dashboardUtils.ts
https://gfw.atlassian.net/browse/TM-1445
> [TM-1445] Default filter

- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/Map-mapbox/utils.ts
- src/components/generic/Loading/LoadingContainerOpacity.stories.tsx
- src/components/generic/Loading/LoadingContainerOpacity.tsx
- src/components/generic/Loading/__snapshots__/LoadingContainerOpacity.stories.storyshot
- src/constants/layers.ts
- src/pages/dashboard/components/ContentOverview.tsx
https://gfw.atlassian.net/browse/TM-1343
> [TM-1343] add loader to popup

- src/components/elements/Table/Table.tsx
- src/components/elements/Table/TableVariants.ts
- src/components/elements/Table/__snapshots__/Table.stories.storyshot
- src/pages/dashboard/components/ContentOverview.tsx
- src/pages/dashboard/index.page.tsx
- src/styles/extended-utilities.css
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?assignee=712020%3Afdaeb363-5553-48e0-9d3c-0af051b4affb&selectedIssue=TM-1314)
> [TM-1314] scroll table

- src/pages/dashboard/components/ContentOverview.tsx
- src/pages/dashboard/components/GraphicIconDashboard.tsx
- src/pages/dashboard/index.page.tsx
> [TM-1407] Small fixes in dashboard table

- src/pages/dashboard/components/GraphicIconDashboard.tsx
> [TM-1407] add space between texts in land use types graph tooltip

- src/pages/dashboard/charts/MultiLineChart.tsx
> [TM-1407] add margin to chart to show complete xaxis label

- src/admin/apiProvider/utils/user.ts
- src/admin/modules/user/const.ts
- src/context/framework.provider.tsx
https://gfw.atlassian.net/browse/TM-1481
> [TM-1481] Add the framework and associated admin user role for the EPA Ghana Pilot

- src/pages/dashboard/components/HeaderDashboard.tsx
- src/pages/dashboard/learn-more/index.page.tsx
https://gfw.atlassian.net/browse/TM-1491
> [TM-1491] add corresponding links to learn more page

- src/components/generic/Sidebar/Sidebar.tsx
https://gfw.atlassian.net/browse/TM-1488
> [TM-1488] add sign out functionality to dashboard side bar

- src/pages/project/[uuid]/tabs/GoalsAndProgress.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1472)
> [TM-1472] add direct seeding survival rate field

- src/components/elements/Inputs/FileInput/FileCardContent.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1456)
> [TM-1456] filter to bin text

- src/pages/dashboard/components/HeaderDashboard.tsx
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1487)
> [TM-1487] Learn More page should have the same hero image as the other dashboard pages

- src/pages/dashboard/components/HeaderDashboard.tsx
[Task Link ](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1490)
> [TM-1490]  BETA branding needs to be better associated with the page title

- src/admin/components/ResourceTabs/InformationTab/components/ReportInformationAside/HighLevelMetrics.tsx
https://gfw.atlassian.net/browse/TM-1482
> [TM-1482] Display total for socioeconomic restoration partners

- src/components/generic/Layout/__snapshots__/MainLayout.stories.storyshot
- src/components/generic/Navbar/__snapshots__/Navbar.stories.storyshot
- src/components/generic/Navbar/navbarItems.ts
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1464)
> [TM-1464] Update TerraMatch homepage when dashboard launches

- src/components/elements/Menu/Menu.tsx
- src/components/elements/TableFilters/Inputs/FilterSearchBoxVariants.ts
- src/pages/dashboard/components/HeaderDashboard.tsx
- src/styles/globals.css
https://gfw.atlassian.net/browse/TM-1473
> [TM-1473] add condition to show menu and change style

- src/pages/dashboard/components/HeaderDashboard.tsx
https://gfw.atlassian.net/browse/TM-1473
> [TM-1473] change style in search bar

- src/components/elements/Map-mapbox/components/DashboardPopup.tsx
https://gfw.atlassian.net/browse/TM-1512
> [TM-1512] Format numbers in dashboard popups

- src/constants/dashboardConsts.ts
- src/pages/dashboard/components/ContentOverview.tsx
- src/pages/dashboard/index.page.tsx
- src/pages/dashboard/learn-more/index.page.tsx
https://gfw.atlassian.net/browse/TM-1530
> [TM-1530] update links to terrafund MRV framework

- src/pages/dashboard/mockedData/dashboard.ts
https://gfw.atlassian.net/browse/TM-1529
> [TM-1529] add Total legend in trees planted section

- src/pages/dashboard/hooks/useDashboardData.ts
- src/pages/dashboard/index.page.tsx
- src/utils/dashboardUtils.ts
https://gfw.atlassian.net/browse/TM-1528
> [TM-1528] add cover image for projects

- src/components/extensive/BlurContainer/BlurContainer.tsx
- src/constants/dashboardConsts.ts
- src/utils/dashboardUtils.ts
https://gfw.atlassian.net/browse/TM-1511
> [TM-1511] change label and fix style issues

- src/admin/components/Alerts/DelayedJobsProgressAlert.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/admin/modules/sites/components/SiteShow.tsx
- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/Map-mapbox/MapControls/CheckPolygonControl.tsx
- src/components/elements/Map-mapbox/MapControls/ProcessBulkPolygonsControl.tsx
- src/generated/apiFetcher.ts
- src/store/apiSlice.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1536)
> [TM-1536] add delayed job progress alert

- src/components/elements/Map-mapbox/MapControls/StyleControl.tsx
- src/components/elements/Map-mapbox/utils.ts
Change the projection used based on the basemap. So the zooms will be correct
> [TM-1508] change projection for street map

- src/admin/modules/organisations/components/OrganisationShow.tsx
- src/pages/organization/[id]/components/edit/getEditOrganisationSteps.ts
https://gfw.atlassian.net/browse/TM-1400
The [BE PR](https://github.com/wri/wri-terramatch-api/pull/588) required a small change to the API surface, which this PR addresses.
This work will _not_ be a part of the next release, so I'll wait to merge until after the release branch is cut today.
> [TM-1400] Organisation now has tree_species_historical

- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/components/elements/Map-mapbox/utils.ts
- src/components/elements/ProgressBar/LinearProgressBar/LineProgressBarMonitored.tsx
https://gfw.atlassian.net/browse/TM-1533
> [TM-1533] Site loading polygon review page

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonItem.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
https://gfw.atlassian.net/browse/TM-1534
> [TM-1534] add indeterminate linear loader for polygon validation data

- src/admin/components/ResourceTabs/MonitoredTab/components/DataCard.tsx
- src/admin/modules/projects/components/ProjectShow.tsx
- src/admin/modules/sites/components/SiteShow.tsx
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1392)
> [TM-1392] show Indicators  in site and project

- src/admin/components/ResourceTabs/MonitoredTab/components/HeaderMonitoredTab.tsx
[task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1392)
> [TM-1392] remove Analyzed

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonItem.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/Polygons.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/components/elements/ProgressBar/LinearProgressBar/LineProgressBarMonitored.tsx
[Task link](https://gfw.atlassian.net/browse/TM-1533?focusedCommentId=34785)
> [TM-1533] indeterminate progress

- src/admin/components/ResourceTabs/PolygonReviewTab/components/Polygons.tsx
[Task link](https://gfw.atlassian.net/browse/TM-1535?focusedCommentId=35013)
> [TM-1535] remove add polygon in polygon review

- src/admin/components/ResourceTabs/MonitoredTab/components/DataCard.tsx
- src/admin/components/ResourceTabs/MonitoredTab/components/EcoRegionDoughnutChart.tsx
- src/constants/dashboardConsts.ts
- src/utils/dashboardUtils.ts
https://gfw.atlassian.net/browse/TM-1466
> [TM-1466] add donut chart for eco region monitored data

- src/admin/components/ResourceTabs/MonitoredTab/components/DataCard.tsx
- src/admin/components/ResourceTabs/MonitoredTab/components/TreesLossBarChart.tsx
- src/admin/components/ResourceTabs/MonitoredTab/hooks/useMonitoredData.ts
- src/utils/dashboardUtils.ts
https://gfw.atlassian.net/browse/TM-1425
> [TM-1425] Tree cover loss graph

- src/admin/components/ResourceTabs/MonitoredTab/components/DataCard.tsx
- src/admin/components/ResourceTabs/MonitoredTab/hooks/useMonitoredData.ts
- src/components/extensive/Modal/ModalRunAnalysis.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1467)
> [TM-1467] add default value tu dropwdown analysis

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/VersionHistory.tsx
- src/components/elements/Inputs/Dropdown/Dropdown.tsx
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?assignee=712020%3Afdaeb363-5553-48e0-9d3c-0af051b4affb&selectedIssue=TM-1559)
> [TM-1559] change style in sidebar site view version dropdown

- src/admin/components/extensive/Modal/ModalApprove.tsx
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?assignee=712020%3Afdaeb363-5553-48e0-9d3c-0af051b4affb&selectedIssue=TM-1557)
> [TM-1557] change style modal approved select all

- src/admin/components/ResourceTabs/MonitoredTab/components/DataCard.tsx
- src/components/elements/Inputs/Dropdown/DropdownVariant.tsx
[task link](https://gfw.atlassian.net/browse/TM-1425?focusedCommentId=35275)
> [TM-1425] text style dropdown monitored indicator

- src/admin/components/ResourceTabs/MonitoredTab/components/DataCard.tsx
- src/admin/components/ResourceTabs/MonitoredTab/components/MonitoredCharts.tsx
- src/admin/components/ResourceTabs/MonitoredTab/components/TreesLossBarChart.tsx
- src/components/elements/Inputs/Dropdown/DropdownVariant.tsx
[Tack link](https://gfw.atlassian.net/browse/TM-1425?focusedCommentId=35339)
> [TM-1425] edit style text monitored sec barChart

- src/components/extensive/WizardForm/utils.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1542)
> [TM-1542] remove percentage based questions warning label

- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/components/elements/Table/Table.tsx
- src/components/elements/Table/__snapshots__/Table.stories.storyshot
[task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?assignee=712020%3Afdaeb363-5553-48e0-9d3c-0af051b4affb&selectedIssue=TM-1561)
> [TM-1561] Edit position sort in table

- src/components/elements/Inputs/TreeSpeciesInput/NonScientificConfirmationModal.tsx
- src/components/elements/Inputs/TreeSpeciesInput/SpeciesAlreadyExistsModal.tsx
- src/components/elements/Inputs/TreeSpeciesInput/TreeSpeciesInput.tsx
- src/components/elements/Inputs/TreeSpeciesInput/TreeSpeciesModal.tsx
https://gfw.atlassian.net/browse/TM-1578
> [TM-1578] Prevent adding a species that is already on the list.

- src/generated/apiFetcher.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1584)
> [TM-1531] polygon validation progress

- src/pages/reports/site-report/[uuid].page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1562)
> [TM-1562] update terrafund report pages

- src/pages/reports/site-report/[uuid].page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1562)
> [TM-1562] update terrafund pages

- src/pages/entity/[entityName]/edit/[uuid]/index.page.tsx
https://gfw.atlassian.net/browse/TM-1590
> [TM-1590] Wait to mount the entity form until the entity has finished loading

- src/pages/entity/[entityName]/edit/[uuid]/index.page.tsx
https://gfw.atlassian.net/projects/TM/versions/10261/tab/release-report-all-issues
> [RELEASE] Ultimate Ulmus Hotfix 2024 12 24

- src/pages/dashboard/charts/DoughnutChart.tsx
- src/pages/dashboard/charts/GroupedBarChart.tsx
- src/pages/dashboard/components/ContentOverview.tsx
- src/pages/dashboard/components/SecDashboard.tsx
https://gfw.atlassian.net/browse/TM-1589
> [TM-1589] add correct reference for tooltip in dashboard

- src/pages/_app.tsx
> [TM-1592] add floatnotif for PD

- src/pages/site/[uuid]/tabs/Overview.tsx
> [TM-1592] remove loader

- src/admin/components/ResourceTabs/MonitoredTab/components/DataCard.tsx
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1593)
> [TM-1593] Hectares By Restoration Strategy Graph Loading Issue

- src/context/dashboard.provider.tsx
- src/pages/dashboard/components/HeaderDashboard.tsx
- src/pages/dashboard/index.page.tsx
https://gfw.atlassian.net/browse/TM-1586
> [TM-1586] include last updated date on dashboard header

- src/admin/utils/forms.ts
- src/components/elements/Inputs/ConditionalInput/ConditionalInput.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1337)
> [TM-1337] add value by default to conditional input

- src/pages/dashboard/charts/CustomTooltip.tsx
- src/pages/dashboard/charts/CustomTooltipJobsCreated.tsx
- src/pages/dashboard/charts/DoughnutChart.tsx
- src/pages/dashboard/charts/GroupedBarChart.tsx
- src/utils/dashboardUtils.ts
https://gfw.atlassian.net/browse/TM-1589
> [TM-1589] add percentages in all tooltips in dashboard

- src/components/elements/Cards/GoalProgressCard/GoalProgressCard.tsx
- src/components/elements/Cards/GoalProgressCard/__snapshots__/GoalProgressCard.stories.storyshot
- src/pages/project/[uuid]/tabs/GoalsAndProgress.tsx
- src/pages/reports/site-report/[uuid].page.tsx
- src/pages/site/[uuid]/tabs/GoalsAndProgress.tsx
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1514)
> [TM-1514] hide tree species new design in PD

- src/context/dashboard.provider.tsx
- src/pages/dashboard/components/HeaderDashboard.tsx
- src/pages/dashboard/hooks/useDashboardData.ts
https://gfw.atlassian.net/browse/TM-1625
> [TM-1625] Add cohort filter to dashboard

- src/admin/components/ResourceTabs/InformationTab/index.tsx
- src/components/extensive/Tables/TreeSpeciesTablePD.tsx
[Task link](https://gfw.atlassian.net/browse/TM-1517?focusedCommentId=36054)
> Tm 1517 web design update admin UI for tree species labels

- src/admin/utils/forms.ts
- src/components/elements/Inputs/ConditionalInput/ConditionalInput.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1631)
> [TM-1631] add logic to default value for conditional

- src/components/elements/Inputs/TreeSpeciesInput/RHFSeedingTableInput.tsx
- src/generated/v3/entityService/entityServiceSchemas.ts
https://gfw.atlassian.net/browse/TM-1577
[v3 PR](https://github.com/wri/terramatch-microservices/pull/43)
> [TM-1577] Use previous counts for seedings

- src/admin/components/ResourceTabs/MonitoredTab/components/DataCard.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1575)
> [TM-1575] add point to link

- src/admin/components/ResourceTabs/InformationTab/index.tsx
- src/components/extensive/Tables/TreeSpeciesTablePD.tsx
- src/pages/project/[uuid]/tabs/GoalsAndProgress.tsx
- src/pages/reports/site-report/[uuid].page.tsx
- src/pages/site/[uuid]/tabs/GoalsAndProgress.tsx
https://gfw.atlassian.net/browse/TM-1601
> [TM-1601] Tree Species Table

- src/components/elements/Inputs/TreeSpeciesInput/TreeSpeciesInput.tsx
- src/components/elements/Inputs/TreeSpeciesInput/__snapshots__/TreeSpeciesInput.stories.storyshot
[Task Link](https://gfw.atlassian.net/browse/TM-1626)
> [TM-1626] add conditional to show trees to be planted

- src/admin/components/ResourceTabs/InformationTab/index.tsx
- src/components/extensive/Tables/TreeSpeciesTablePD.tsx
https://gfw.atlassian.net/browse/TM-1603
> [TM-1603] add condition for site report species table

- src/pages/dashboard/components/HeaderDashboard.tsx
https://gfw.atlassian.net/browse/TM-1625?focusedCommentId=36291
> [TM-1625] remove programme filter and change cohort position

- src/pages/dashboard/components/HeaderDashboard.tsx
https://gfw.atlassian.net/browse/TM-1625?focusedCommentId=36291
> [TM-1625] remove programme filter and change cohort position (#823)

- src/components/extensive/Tables/TreeSpeciesTablePD.tsx
https://gfw.atlassian.net/browse/TM-1602?focusedCommentId=36355
> [TM-1603] add the correct attribute to sum for tree species tables

- src/pages/dashboard/project-list/index.page.tsx
https://gfw.atlassian.net/browse/TM-1625?focusedCommentId=36386
> [TM-1625] sort project list in dashboard

- src/components/elements/Cards/GoalProgressCard/GoalProgressCard.tsx
- src/components/elements/Cards/GoalProgressCard/__snapshots__/GoalProgressCard.stories.storyshot
- src/pages/project/[uuid]/tabs/GoalsAndProgress.tsx
- src/pages/reports/site-report/[uuid].page.tsx
- src/pages/site/[uuid]/tabs/GoalsAndProgress.tsx
[Task link](https://gfw.atlassian.net/browse/TM-1514?focusedCommentId=36363)
> Tm 1514 Remove tree species PD

- src/admin/components/ResourceTabs/InformationTab/index.tsx
- src/components/extensive/Tables/TreeSpeciesTablePD.tsx
https://gfw.atlassian.net/browse/TM-1602?focusedCommentId=36395
> [TM-1602] add data to seedling table

- src/admin/components/ResourceTabs/InformationTab/index.tsx
- src/admin/utils/forms.ts
- src/components/elements/Inputs/ConditionalInput/ConditionalInput.tsx
- src/components/extensive/WizardForm/types.ts
- src/generated/v3/entityService/entityServiceSchemas.ts
- src/helpers/customForms.ts
- src/hooks/useGetCustomFormSteps/__snapshots__/useGetCustomFormSteps.test.ts.snap
- src/hooks/useGetCustomFormSteps/formSchema.json
[Task Link](https://gfw.atlassian.net/browse/TM-1629)
> [TM-1629] address comments with conditionals

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
- src/admin/components/extensive/Modal/ModalApprove.tsx
- src/components/elements/Map-mapbox/MapControls/CheckPolygonControl.tsx
- src/components/extensive/Modal/ModalFixOverlaps.tsx
- src/components/extensive/Modal/ModalSubmit.tsx
- src/helpers/polygonValidation.ts
Within country validation is only a warning, not a blocker for approval
> [TM-1651] remove within country validator

- src/components/extensive/Tables/TreeSpeciesTablePD.tsx
https://gfw.atlassian.net/browse/TM-1601?focusedCommentId=36474
> [TM-1603] show multiple icons in tree species table

- src/admin/utils/forms.ts
- src/components/elements/Inputs/ConditionalInput/ConditionalInput.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1629)
> [TM-1629] conditional answers

- src/admin/utils/forms.ts
- src/components/elements/Inputs/ConditionalInput/ConditionalInput.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1629)
> [TM-1629] handle null and false cases in conditionals

- src/pages/project/[uuid]/tabs/GoalsAndProgress.tsx
- src/pages/site/[uuid]/tabs/GoalsAndProgress.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1514)
> [TM-1514] update banner progress goals

- src/admin/components/EntityEdit/EntityEdit.tsx
- src/hooks/useFormUpdate.ts
- src/pages/entity/[entityName]/edit/[uuid]/EditEntityForm.tsx
https://gfw.atlassian.net/browse/TM-1640
[PHP PR](https://github.com/wri/wri-terramatch-api/pull/670)
> [TM-1640] Avoid overlapping and superfluous form updates.

- src/pages/project/[uuid]/tabs/Details.tsx
https://gfw.atlassian.net/browse/TM-1639
https://gfw.atlassian.net/browse/TM-1638
> [TM-1638][TM-1639] Fix use of detailed intervention types on project details

- src/components/elements/Inputs/TreeSpeciesInput/TreeSpeciesInput.tsx
https://gfw.atlassian.net/browse/TM-1658
> [TM-1658] Use different column headers for nursery seedlings.

- src/pages/reports/site-report/[uuid].page.tsx
https://gfw.atlassian.net/browse/TM-1615
> [TM-1615] add references for terrafund site report landing page

- src/pages/reports/site-report/[uuid].page.tsx
https://gfw.atlassian.net/browse/TM-1616
> [TM-1616] add references for hbf site report landing page

- src/admin/components/Actions/ShowActions.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1637)
> [TM-1637] fix permissions with edit user

- src/pages/project/[uuid]/tabs/GoalsAndProgress.tsx
https://gfw.atlassian.net/browse/TM-1608
> [TM-1608] add corresponding data for tree planting progress

- src/pages/project/[uuid]/tabs/Details.tsx
https://gfw.atlassian.net/browse/TM-1639
> [TM-1639] Use the translated title of each option.

- src/components/elements/Inputs/TreeSpeciesInput/TreeSpeciesInput.tsx
https://gfw.atlassian.net/browse/TM-1658
> [TM-1658] Tweak the language for nursery vs nursery report.

- src/admin/components/Actions/ShowActions.tsx
- src/admin/hooks/useCanUserEdit.ts
- src/admin/modules/user/components/UserList.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1637)
> [TM-1637] framework admin can't delete

- src/pages/project/[uuid]/tabs/GoalsAndProgress.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1610)
> [TM-1610] replace values to goal progress card

- src/components/extensive/Tables/TreeSpeciesTablePD.tsx
- src/pages/project/[uuid]/tabs/GoalsAndProgress.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1609)
> [TM-1609] show table non tree to project HBF

- src/admin/components/Dialogs/FrameworkSelectionDialog.tsx
- src/generated/apiComponents.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1657)
> [TM-1657] add export pm

- src/admin/components/ResourceTabs/MonitoredTab/components/ProgressGoalsDoughnutChart.tsx
- src/pages/project/[uuid]/tabs/GoalsAndProgress.tsx
- src/pages/site/[uuid]/components/GoalsAndProgressEntityTab.tsx
- src/pages/site/[uuid]/tabs/GoalsAndProgress.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1610)
> [TM-1610] conditional update to ALL_TF and other small changes

- src/components/extensive/BlurContainer/BlurContainer.tsx
- src/constants/dashboardConsts.ts
- src/pages/project/[uuid]/tabs/GoalsAndProgress.tsx
- src/pages/site/[uuid]/tabs/GoalsAndProgress.tsx
https://gfw.atlassian.net/browse/TM-1608
> [TM-1608, TM-1611, TM-1612] show tables for corresponding frameworks

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
update criteria data on sidebar
> [TM-1667] reload data after call validation in sidebad

- src/admin/components/Dialogs/FrameworkSelectionDialog.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1657)
> [TM-1657] fix export report bug

- src/admin/components/ResourceTabs/InformationTab/components/ProjectInformationAside/HighLevelMetrics.tsx
- src/constants/dashboardConsts.ts
- src/pages/dashboard/components/ContentOverview.tsx
- src/pages/dashboard/components/HeaderDashboard.tsx
- src/pages/dashboard/components/SecDashboard.tsx
- src/pages/dashboard/constants/tooltips.ts
- src/pages/dashboard/index.page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1358)
> Tm 1358 dashboard translations

- src/components/extensive/Tables/TreeSpeciesTablePD.tsx
- src/pages/project/[uuid]/tabs/GoalsAndProgress.tsx
- src/pages/site/[uuid]/tabs/GoalsAndProgress.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1614)
[Task Link](https://gfw.atlassian.net/browse/TM-1612)
> [TM-1614] add non trees progress section to hbf site

- src/components/extensive/Tables/DisturbancesTablePD.tsx
https://gfw.atlassian.net/browse/TM-1729
> [TM-1729] add null check in disturbance data table

- src/pages/dashboard/components/GraphicIconDashboard.tsx
https://gfw.atlassian.net/browse/TM-1646
> [TM-1646] sort list in land use type in dashboard

- src/pages/reports/nursery-report/[uuid].page.tsx
- src/pages/reports/site-report/[uuid].page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1723)
> [TM-1723] fix breadcrumb on site report

- src/pages/reports/nursery-report/[uuid].page.tsx
- src/pages/reports/site-report/[uuid].page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1691)
> [TM-1691] display name on entity header

- src/components/extensive/Tables/DisturbancesTablePD.tsx
https://gfw.atlassian.net/browse/TM-1729
> [TM-1729] add null check in disturbance data table for site report landing page

- src/components/extensive/Tables/DisturbancesTablePD.tsx
https://gfw.atlassian.net/browse/TM-1729
> [RELEASE] X-Rayed Xylocarpus Hotfix 2025 02 07

- src/components/elements/Tabs/Secondary/SecondaryTabs.tsx
- src/components/elements/Tabs/Secondary/SecuandaryTabsVariants.ts
- src/pages/dashboard/impact-story/[uuid]/index.page.tsx
- src/pages/dashboard/impact-story/components/CardImpactStory.tsx
- src/pages/dashboard/impact-story/components/TabImpactStory.tsx
[task link](https://gfw.atlassian.net/browse/TM-1617)
> [TM-1617] dashboard impact story style

- src/admin/components/EntityEdit/EntityEdit.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1691)
> [TM-1691] fix display report name entity

- src/pages/project/[uuid]/tabs/GoalsAndProgress.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1731)
> [TM-1731] showing correct tree survival rate

- src/admin/apiProvider/authProvider.ts
- src/admin/hooks/useCanUserEdit.ts
- src/admin/hooks/useGetUserRole.ts
- src/admin/modules/user/components/UserList.tsx
https://gfw.atlassian.net/browse/TM-1735
> [TM-1735] Fix console error spam on the user list page.

- src/pages/project/[uuid]/tabs/Details.tsx
https://gfw.atlassian.net/browse/TM-1727
> [TM-1727] Fix data source for District field on projects' PD view.

- src/admin/components/ResourceTabs/MonitoredTab/components/MonitoredCharts.tsx
- src/pages/dashboard/components/ContentOverview.tsx
- src/pages/dashboard/components/HeaderDashboard.tsx
- src/pages/dashboard/constants/tooltips.ts
- src/pages/dashboard/impact-story/index.page.tsx
- src/pages/dashboard/project-list/index.page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1692)
> [TM-1692] add missing or new dashboard translations

- src/components/extensive/Modal/ModalStory.tsx
https://gfw.atlassian.net/browse/TM-1702
> [TM-1702] add correct reference for image in impact sotry component

- src/admin/modules/impactStories/components/ImpactStories.tsx
- src/admin/modules/impactStories/components/ImpactStoriesList.tsx
- src/admin/modules/impactStories/components/ImpactStoryForm.tsx
- src/admin/modules/impactStories/components/StyledFileUploadInput.tsx
- src/admin/modules/impactStories/components/StyledInputs.tsx
- src/pages/dashboard/impact-story/components/SectionShare.tsx
[Task Link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?assignee=712020%3Afdaeb363-5553-48e0-9d3c-0af051b4affb&assignee=712020%3Ac0284fef-13c2-4728-86c5-08b1988e2c2a&assignee=712020%3A9a751e57-2690-474c-aafd-f846dac20d53&selectedIssue=TM-1702)
> Tm 1702 impact story admin and content management system dev

- src/components/elements/Map-mapbox/hooks/useMap.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1730)
> [TM-1730] add minZoom param -> 2.0 for limit zoom level

- src/admin/modules/impactStories/components/ImpactStoryForm.tsx
- src/components/extensive/Modal/ModalShareImpactStory.tsx
- src/components/extensive/Modal/ModalStory.tsx
- src/pages/dashboard/impact-story/[uuid]/index.page.tsx
- src/pages/dashboard/impact-story/components/CardImpactStory.tsx
- src/pages/dashboard/impact-story/components/SectionShare.tsx
https://gfw.atlassian.net/browse/TM-1706
> [TM-1706] add share functionality

- src/components/extensive/Modal/ModalStory.tsx
- src/pages/dashboard/hooks/useDashboardData.ts
https://gfw.atlassian.net/browse/TM-1704
> [TM-1704] add image to the impact story modal

- src/admin/components/ResourceTabs/InformationTab/components/ProjectInformationAside/QuickActions.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1744)
> [TM-1744] fix download geojson

- src/admin/modules/impactStories/components/ImpactStories.tsx
- src/admin/modules/impactStories/components/ImpactStoryForm.tsx
- src/admin/modules/impactStories/hooks/useImpactStoryForm.ts
- src/pages/dashboard/impact-story/components/SectionShare.tsx
https://gfw.atlassian.net/browse/TM-1702
> [TM-1702] disable publish button when creating or updating

- src/admin/modules/impactStories/components/ImpactStoriesList.tsx
- src/admin/modules/impactStories/components/ImpactStoryForm.tsx
- src/pages/dashboard/hooks/useDashboardData.ts
- src/pages/dashboard/impact-story/[uuid]/index.page.tsx
- src/pages/dashboard/impact-story/components/TabImpactStory.tsx
https://gfw.atlassian.net/browse/TM-1702
> [TM-1702] check undefined value

- src/components/extensive/Modal/ModalStory.tsx
https://gfw.atlassian.net/browse/TM-1702
> [TM-1702] Add correct reference to image in impact stories

- src/components/elements/Notification/FloatNotification.tsx
[Task Lnk](https://gfw.atlassian.net/browse/TM-1711)
These lines of code have been commented out as they will be used later.
> [TM-1711] hide cancel button

- src/pages/project/[uuid]/tabs/Details.tsx
https://gfw.atlassian.net/browse/TM-1747
> [TM-1747] add planting end date in project details as PD

- src/components/extensive/Modal/ModalStory.tsx
https://gfw.atlassian.net/browse/TM-1785
> [TM-1785] remove thumbnail from preview component in impact stories

- src/pages/dashboard/impact-story/[uuid]/index.page.tsx
https://gfw.atlassian.net/browse/TM-1786
> [TM-1786] remove thumbnain from full screen impact story

- src/pages/dashboard/components/ContentOverview.tsx
- src/pages/dashboard/hooks/useDashboardData.ts
https://gfw.atlassian.net/browse/TM-1790
> [TM-1790] Content Display

- src/components/extensive/Modal/ModalStory.tsx
- src/pages/dashboard/components/ContentOverview.tsx
- src/pages/dashboard/hooks/useDashboardData.ts
- src/pages/dashboard/impact-story/[uuid]/index.page.tsx
- src/pages/dashboard/index.page.tsx
[Jira Release](https://gfw.atlassian.net/projects/TM/versions/10434/tab/release-report-all-issues)
> [RELEASE] Youthful Yucca hotfix 2025 02 21

- src/pages/dashboard/components/ContentOverview.tsx
https://gfw.atlassian.net/browse/TM-1765
> [TM-1765] Fix hook usage

- src/pages/dashboard/index.page.tsx
https://gfw.atlassian.net/browse/TM-1788
> [TM-1788] include organization name in project page in dashboard

- src/pages/dashboard/charts/GroupedBarChart.tsx
- src/pages/dashboard/charts/SimpleBarChart.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1692)
> [TM-1692] add missing translations from simple bar chart

- src/admin/components/ResourceTabs/InformationTab/components/ProjectInformationAside/HighLevelMetrics.tsx
- src/admin/components/ResourceTabs/InformationTab/components/ReportInformationAside/HighLevelMetrics.tsx
- src/admin/components/ResourceTabs/InformationTab/components/SiteInformationAside/HighLevelMetrics.tsx
https://gfw.atlassian.net/browse/TM-1416
> [TM-1416] add ANR in high level metrics

- src/pages/dashboard/charts/GroupedBarChart.tsx
- src/pages/dashboard/charts/SimpleBarChart.tsx
[Jira Release](https://gfw.atlassian.net/projects/TM/versions/10500/tab/release-report-all-issues)
> [RELEASE] Youthful Yucca hotfix 2025 02 25

- src/admin/components/ResourceTabs/InformationTab/components/ProjectInformationAside/HighLevelMetrics.tsx
https://gfw.atlassian.net/browse/TM-1416
> [TM-1416] add correct label for tree restored via ANR

- src/admin/components/ResourceTabs/AuditLogTab/AuditLogTab.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/AuditLogSiteTabSelection.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogEntityStatusSide.tsx
- src/hooks/AuditStatus/useLoadEntityList.ts
- src/pages/project/[uuid]/tabs/AuditLog.tsx
- src/pages/reports/project-report/[uuid].tsx
- src/pages/reports/project-report/tabs/AuditLog.tsx
- src/pages/site/[uuid]/tabs/AuditLog.tsx
> [TM-1058] add nursery log tab

- src/components/extensive/WizardForm/FormFooter.tsx
- src/components/extensive/WizardForm/FormStep.tsx
- src/components/extensive/WizardForm/index.tsx
- tailwind.config.js
[Task Link](https://gfw.atlassian.net/browse/TM-1697)
> TM-1697 sticky footbar for forms

- src/admin/components/ResourceTabs/AuditLogTab/AuditLogTab.tsx
> change framework_key -> frameworkKey

- src/admin/components/ResourceTabs/AuditLogTab/AuditLogTab.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/AuditLogSiteTabSelection.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogEntityStatus.tsx
- src/hooks/AuditStatus/useAuditLogActions.ts
- src/hooks/AuditStatus/useLoadEntityList.ts
- src/pages/reports/project-report/tabs/AuditLog.tsx
> [TM-1058] audit log

- src/admin/components/ResourceTabs/AuditLogTab/AuditLogTab.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/AuditLogSiteTabSelection.tsx
- src/pages/project/[uuid]/tabs/AuditLog.tsx
> [TM-1058] add entity level param

- src/admin/components/ResourceTabs/AuditLogTab/AuditLogTab.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/AuditLogSiteTabSelection.tsx
- src/admin/components/ResourceTabs/AuditLogTab/components/SiteAuditLogEntityStatus.tsx
- src/pages/project/[uuid]/tabs/AuditLog.tsx
- src/pages/reports/project-report/tabs/AuditLog.tsx
> [TM-1058] changes to audit log section (site report, nursery report)

- src/admin/components/ResourceTabs/InformationTab/index.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1743)
> [TM-1743] add seedlings species breakdown in nusery reports

- src/admin/components/ResourceTabs/AuditLogTab/components/AuditLogSiteTabSelection.tsx
> remove 'status' text

- src/components/extensive/Tables/TreeSpeciesTablePD.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1743)
> [TM-1743] tree species table conditionals for nursery report

- src/pages/project/[uuid]/tabs/GoalsAndProgress.tsx
Found a problem locally that affects the release.
> [NO TICKET] Fix goals and progress ANR for projects.

- src/components/extensive/WizardForm/index.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1242)
> [TM-1242] Force form to save

- src/components/extensive/DemographicsCollapseGrid/types.ts
https://gfw.atlassian.net/browse/TM-1839
> [TM-1839] Use HBF ages for HBF jobs / benes

- src/components/extensive/DemographicsCollapseGrid/types.ts
https://gfw.atlassian.net/projects/TM/versions/10599/tab/release-report-all-issues
> [RELEASE] Zealous Ziziphus hotfix 2026 03 07

- src/connections/SitePolygons.ts
- src/constants/environment.ts
https://gfw.atlassian.net/browse/TM-1759
> [TM-1759] include research service url in const Services

- src/pages/nursery/[uuid]/tabs/Overview.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1325)
> [TM-1325] change property nursery_type -> type

- src/pages/site/[uuid]/tabs/Details.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1746)
> [TM-1746] change description for landscapeCommunityContribution

- src/admin/components/Dialogs/FrameworkSelectionDialog.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1851)
> [TM-1851] allow framework admins to exports whole framework reports

- src/admin/modules/impactStories/components/QuillEditor.tsx
- src/components/extensive/Modal/ModalStory.tsx
- src/pages/dashboard/impact-story/[uuid]/index.page.tsx
- src/styles/extended-components.css
https://gfw.atlassian.net/browse/TM-1854
> [TM-1854] enlarge youtube video in impact  story

- src/admin/modules/projects/components/ProjectsList.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-429)
> [TM-429] add new fields in project list table

- src/admin/components/ResourceTabs/MonitoredTab/components/DataCard.tsx
- src/components/elements/ServerSideTable/ServerSideTable.tsx
- src/components/extensive/Tables/SitePolygonsTable.tsx
- src/connections/SitePolygons.ts
- src/generated/v3/researchService/researchServiceComponents.ts
- src/generated/v3/researchService/researchServiceSchemas.ts
- src/utils/MonitoredIndicatorUtils.ts
https://gfw.atlassian.net/browse/TM-1825
> [TM-1825] Pagination monitoring indicator

- src/pages/project-pitches/components/tabs/PitchOverviewTab.tsx
https://gfw.atlassian.net/browse/TM-1808
> [TM-1808] zoom to country in project pitch overview

- src/components/elements/Inputs/TreeSpeciesInput/useAutocompleteSearch.ts
A drive-by fix for something I broke earlier in the sprint and didn't notice.
> [FIX] Fix scientific name search

- src/admin/apiProvider/dataProviders/applicationDataProvider.ts
- src/generated/apiComponents.ts
- src/generated/apiRequestBodies.ts
- src/generated/apiSchemas.ts
- src/pages/applications/[id].page.tsx
- src/pages/applications/components/ApplicationStatus.tsx
- src/pages/applications/request-more-information/[id].page.tsx
https://gfw.atlassian.net/browse/TM-1853
This makes the necessary FE changes for the related BE PR: https://github.com/wri/wri-terramatch-api/pull/753, and will likely not successfully build until that one is deployed to staging.
> [TM-1853] Handle the removal of current_submission from the full application read endpoints

- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
https://gfw.atlassian.net/browse/TM-1853
> [TM-1853] Regenerate API layer (no further code changes needed)

- src/admin/modules/nurseries/components/NurseriesList.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1767)
> [TM-1767] add missing properties

- src/pages/dashboard/components/DashboardBreadcrumbs.tsx
- src/pages/dashboard/components/HeaderDashboard.tsx
- src/pages/dashboard/components/SecDashboard.tsx
- src/pages/dashboard/index.page.tsx
https://gfw.atlassian.net/browse/TM-1858
> [TM-1858] dashboard performance

- src/admin/components/ResourceTabs/InformationTab/components/ProjectInformationAside/QuickActions.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-660)
> [TM-660] enable site reports and nursery reports export

- src/components/extensive/DemographicsCollapseGrid/DemographicsCollapseGrid.tsx
https://gfw.atlassian.net/browse/TM-1888
> [TM-1888] Fix the type used for filtering in onChange.

- src/admin/components/ResourceTabs/InformationTab/components/ProjectInformationAside/QuickActions.tsx
- src/admin/modules/nurseries/components/NurseriesList.tsx
- src/admin/modules/nurseryReports/components/NurseryReportsList.tsx
- src/admin/modules/projectReports/components/ProjectReportsList.tsx
- src/admin/modules/projects/components/ProjectsList.tsx
- src/admin/modules/siteReports/components/SiteReportsList.tsx
- src/admin/modules/sites/components/SitesList.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1852)
[Task Link](https://gfw.atlassian.net/browse/TM-1870)
> [TM-1852] update source values and add perpage to auto complete input

- src/pages/dashboard/components/DashboardBreadcrumbs.tsx
- src/pages/dashboard/components/HeaderDashboard.tsx
- src/pages/dashboard/components/SecDashboard.tsx
- src/pages/dashboard/index.page.tsx
https://gfw.atlassian.net/browse/TM-1858
> [TM-1858] dashboard performance cache

- src/components/elements/Inputs/DataTable/RHFFundingTypeDataTable.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1841)
> [TM-1841] update select funding year options

- src/components/elements/Cards/ProjectCard/ProjectCard.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1913)
> [TM-1913] add missing property to entity table

- src/utils/dashboardUtils.ts
https://gfw.atlassian.net/browse/TM-1909
> [TM-1909] add label when value is null

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/AttributeInformation.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/components/elements/Map-mapbox/Map.tsx
- src/context/sitePolygon.provider.tsx
- src/hooks/paginated/useLoadCriteriaSite.ts
Dont call for all site polygons related on edit values
> [TM-1867] update data and dont reload

- src/components/elements/Inputs/ConditionalInput/ConditionalInput.tsx
- src/components/extensive/WizardForm/index.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1923)
- Ensures that the most recent data is correctly reflected in the form and avoids inconsistencies in the form state.
> [TM-1923] conditional issues in reports

- src/constants/dashboardConsts.ts
- src/pages/dashboard/charts/SimpleBarChart.tsx
- src/utils/dashboardUtils.ts
https://gfw.atlassian.net/browse/TM-1795
> [TM-1795] add no strategy identified in bar chart

- src/pages/dashboard/charts/CustomTooltip.tsx
- src/utils/dashboardUtils.ts
https://gfw.atlassian.net/browse/TM-1917
> [TM-1917] standardize tooltips for graphs

- src/components/extensive/DemographicsCollapseGrid/DemographicsDisplay.tsx
- src/components/extensive/DemographicsCollapseGrid/types.ts
- src/components/extensive/WizardForm/FieldMapper.tsx
- src/components/extensive/WizardForm/FormSummaryRow.tsx
- src/components/extensive/WizardForm/types.ts
- src/components/extensive/WizardForm/utils.ts
- src/generated/v3/entityService/entityServiceSchemas.ts
- src/helpers/customForms.ts
https://gfw.atlassian.net/browse/TM-1842
The build on this branch depends on some API updates on the v3 PR, so the build step will not pass until that has been merged and deployed.
> [TM-1842] Support for employees and indirect-beneficiaries as demographic types

- src/components/extensive/BlurContainer/BlurContainer.tsx
- src/connections/Login.ts
- src/pages/auth/login/index.page.tsx
https://gfw.atlassian.net/browse/TM-1920
> [TM-1920] implement post-login redirect to original page

- src/connections/Entity.ts
- src/generated/v3/entityService/entityServiceComponents.ts
The web build was broken by some last minute changes I requested on https://github.com/wri/terramatch-microservices/pull/120. This gets it working again
> Fix web build on staging.

- src/admin/components/ResourceTabs/InformationTab/index.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1928)
> [TM-1928] change property name nothing_to_report -> nothingToReport

- src/pages/dashboard/components/HeaderDashboard.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1938)
> [TM-1938] hide last updated text on homepage

- src/helpers/customForms.ts
https://gfw.atlassian.net/browse/TM-1892
> [TM-1892] Use an old system to support GADM level 1 multi select in the new application fields.

- src/components/elements/Inputs/Dropdown/RHFDropdown.tsx
https://gfw.atlassian.net/browse/TM-1892
> [TM-1892] Memoize the options being sent to Dropdown.

- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/admin/components/extensive/Modal/ModalApprove.tsx
- src/components/extensive/Modal/ModalSubmit.tsx
- src/components/extensive/Modal/components/CollapsibleRow.tsx
- src/pages/site/[uuid]/tabs/Overview.tsx
https://gfw.atlassian.net/browse/TM-1956
> [TM-1956] update submit and approve modals with new validation status

- src/helpers/customForms.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1829)
> [TM-1829] update validation de normalized function

- src/components/elements/Notification/FloatNotification.tsx
https://gfw.atlassian.net/browse/TM-1711
> [TM-1711] Notifications allow user to cancel an action

- src/components/elements/Inputs/MyAccountDropdown/MyAccountDropdown.tsx
- src/connections/Login.ts
- src/utils/Bootstrap.tsx
https://gfw.atlassian.net/browse/TM-1825
> [TM-1925] Fix login redirection to dashboard/learn-more

- src/pages/auth/signup/index.page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2010)
> [TM-2010] Unable to sign up as a new user

- src/components/elements/Inputs/Dropdown/RHFDropdown.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2017)
> [TM-2017] fix parameter type passed to gadm options

- src/components/elements/Inputs/Dropdown/RHFDropdown.tsx
https://gfw.atlassian.net/browse/TM-2017
> [TM-2017] Parent codes is often already an array.

- src/components/elements/Inputs/Dropdown/RHFDropdown.tsx
https://gfw.atlassian.net/browse/TM-1958
> [TM-1958] If the parent field is null, the parent codes should also be null, not an empty array

- src/components/generic/Layout/DashboardLayout.tsx
- src/pages/dashboard/components/HeaderDashboard.tsx
- src/pages/dashboard/index.page.tsx
https://gfw.atlassian.net/browse/TM-2012
> [TM-2012] use countries hook in dashboard

- src/components/elements/MapPolygonPanel/MapEditPolygonPanel.tsx
in PD, checklist was not loading
> [TM-2020] load checklist

- src/pages/dashboard/project-list/index.page.tsx
https://gfw.atlassian.net/browse/TM-2021
> [TM-2021] add correct name for the active project table

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx
- src/admin/components/extensive/Modal/ModalApprove.tsx
- src/components/elements/Map-mapbox/MapControls/CheckPolygonControl.tsx
- src/components/elements/MapPolygonPanel/MapMenuPanelItem.tsx
- src/components/extensive/Modal/ModalFixOverlaps.tsx
- src/components/extensive/Modal/ModalSubmit.tsx
- src/helpers/polygonValidation.ts
Add data complete to be verified
> [TM-1974] include completed data into validation required

- src/admin/components/ResourceTabs/InformationTab/components/ReportInformationAside/HighLevelMetrics.tsx
- src/generated/v3/entityService/entityServiceSchemas.ts
https://gfw.atlassian.net/browse/TM-1969
> [TM-1969] Display aggregated task workdays.

- src/generated/apiFetcher.ts
https://gfw.atlassian.net/browse/TM-2026
> [TM-2026] Quiet down v1/2 fetch errors in sentry.

- src/admin/components/ResourceTabs/ReportTab/hooks/useReportData.ts
- src/connections/SitePolygons.ts
https://gfw.atlassian.net/browse/TM-2027
> [TM-2027] max render update

- src/generated/apiComponents.ts
- src/generated/apiRequestBodies.ts
- src/generated/apiSchemas.ts
- src/pages/form/[id]/index.page.tsx
- src/pages/form/cards/ApplicationsTable.tsx
https://gfw.atlassian.net/browse/TM-2022
Build will fail until https://github.com/wri/wri-terramatch-api/pull/847 is merged and deployed.
> [TM-2022] Display active applications on the application start page.

- src/components/extensive/ActionTracker/ActionTracker.tsx
- src/components/extensive/ActionTracker/ActionTrackerCardRow.tsx
- src/components/extensive/ActionTracker/__snapshots__/ActionTracker.stories.storyshot
- src/components/extensive/ActionTracker/__snapshots__/ActionTrackerCardRow.stories.storyshot
- src/components/extensive/ActionTracker/cards/ApplicationsCard.tsx
- src/components/extensive/ActionTracker/cards/__snapshots__/ApplicationsCard.stories.storyshot
https://gfw.atlassian.net/browse/TM-2023
This PR depends on code in https://github.com/wri/wri-terramatch-website/pull/1200, so is based on it. Will be merged to staging after that PR is merged.
Build will fail until https://github.com/wri/wri-terramatch-api/pull/847 has been merged and deployed.
> [TM-2023] Include updated at and updated by in the action tracker card.

- src/components/elements/Map-mapbox/components/DashboardPopup.tsx
- src/components/elements/Map-mapbox/components/PopupMobile.tsx
- src/connections/EntityAssociation.ts
- src/generated/apiComponents.ts
- src/generated/v3/entityService/entityServiceComponents.ts
- src/generated/v3/entityService/entityServiceSchemas.ts
- src/pages/dashboard/components/DashboardBreadcrumbs.tsx
- src/pages/dashboard/hooks/useDashboardData.ts
- src/pages/dashboard/hooks/usePopupsData.ts
- src/pages/dashboard/index.page.tsx
- src/utils/dashboardUtils.ts
DEPRECATE:
/project-data/{uuid} - Detailed project information
/project-details/{project} - Detailed project profile 
And migrate the use of data from project Full DTO in V3.
This affects the project page in DASHBOARD and POPUPs for DASHBOARD map
> [TM-2009] replace project data in dashboard

- src/components/extensive/ActionTracker/cards/ApplicationsCard.tsx
- src/components/extensive/ActionTracker/cards/__snapshots__/ApplicationsCard.stories.storyshot
- src/components/extensive/WizardForm/WizardFormIntro.tsx
- src/pages/form/[id]/index.page.tsx
https://gfw.atlassian.net/browse/TM-2023
https://gfw.atlassian.net/browse/TM-2022
Took care of feedback on both of the above tickets in this one branch.
> [TM-2022/2023] Application product feedback

- src/components/generic/Layout/DashboardLayout.tsx
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
- src/pages/auth/create-account/index.page.tsx
https://gfw.atlassian.net/browse/TM-2007
> [TM-2007] remove countries endpoint

- src/helpers/customForms.ts
[Task Link](https://gfw.atlassian.net/browse/TM-2044)
> [TM-2044] fix: add validation to long-text field

- src/admin/apiProvider/dataNormalizers/formDataNormalizer.ts
- src/admin/apiProvider/dataProviders/stageDataProvider.ts
- src/admin/apiProvider/utils/entryFormat.ts
- src/admin/components/ResourceTabs/MonitoredTab/components/DataCard.tsx
- src/components/elements/ImageGallery/ImageGalleryItem.tsx
- src/components/elements/MapPolygonPanel/VersionInformation.tsx
- src/hooks/useReportingWindow.ts
> [TM-2046] fix error

- src/components/extensive/WizardForm/utils.ts
https://gfw.atlassian.net/browse/TM-2048
> [TM-2048] Application form fix

- src/admin/modules/form/components/FormBuilder/QuestionArrayInput.tsx
- src/components/elements/Inputs/FinancialTableInput/RHFFinancialIndicatorTable.tsx
- src/components/extensive/WizardForm/FormSummaryRow.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1943)
> [TM-1943] add collection conditional to financial section

- src/admin/modules/form/components/FormBuilder/QuestionArrayInput.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1943)
> [TM-1943] update financial indicators entity UI

- src/admin/modules/form/components/FormBuilder/QuestionArrayInput.tsx
- src/components/elements/Inputs/FinancialTableInput/RHFFinancialIndicatorTable.tsx
- src/components/elements/Inputs/FinancialTableInput/types.ts
- src/components/extensive/WizardForm/FormSummaryRow.tsx
- src/pages/applications/request-more-information/[id].page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1943)
> [TM-1943] update financial indicators entity report and application

- src/components/elements/Inputs/Dropdown/RHFDropdown.tsx
- src/pages/organization/create/getCreateOrganisationSteps.ts
https://gfw.atlassian.net/browse/TM-2073
> [TM-2073] RHFDropdown unfortunately ends up needing that formhook.trigger() afterall

- src/components/elements/Inputs/Dropdown/RHFDropdown.tsx
- src/pages/organization/create/getCreateOrganisationSteps.ts
https://gfw.atlassian.net/projects/TM/versions/11094/tab/release-report-all-issues
> [RELEASE] Elegant Emerald Hotfix 2025-05-22

- src/generated/apiComponents.ts
- src/pages/auth/set-password/[token].page.tsx
https://gfw.atlassian.net/browse/TM-2065
> [TM-2065] Use the preferred locale for the set password page.

- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
- src/generated/v3/entityService/entityServiceComponents.ts
- src/generated/v3/entityService/entityServiceSchemas.ts
- src/pages/dashboard/hooks/useDashboardData.ts
https://gfw.atlassian.net/browse/TM-2036
> [TM-2036] get project light resource from v3 for dashboard

- src/components/elements/Inputs/Input/Input.tsx
- src/helpers/customForms.ts
https://gfw.atlassian.net/browse/TM-2053
> [TM-2053] fix lat and log validation message

- src/connections/Entity.ts
- src/pages/dashboard/hooks/useDashboardData.ts
https://gfw.atlassian.net/browse/TM-2036
> [TM-2036] add condition for new filters for dashboard

- src/admin/modules/nurseryReports/components/NurseryReportsList.tsx
- src/admin/modules/siteReports/components/SiteReportsList.tsx
- src/constants/options/status.ts
- src/generated/v3/entityService/entityServiceComponents.ts
https://gfw.atlassian.net/browse/TM-2016
> [TM-2016] Add filtering based on nothing to report

- src/generated/v3/dashboardService/dashboardServiceComponents.ts
- src/pages/dashboard/hooks/useDashboardData.ts
> [TM-2008] change property name

- src/hooks/useMessageValidations.ts
https://gfw.atlassian.net/browse/TM-2064
> [TM-2064] update validation message for plant start date

- src/pages/dashboard/hooks/useDashboardData.ts
- src/pages/dashboard/hooks/useDashboardTreeSpeciesData.ts
https://gfw.atlassian.net/browse/TM-2035
> [TM-2035] Add organization type parameter to tree species data hook

- src/pages/dashboard/hooks/useDashboardData.ts
https://gfw.atlassian.net/browse/TM-2036
> [TM-2036] show centroids for visitors

- src/components/extensive/WizardForm/utils.ts
[Task Link](https://gfw.atlassian.net/browse/TM-2075)
> [TM-2075] add boolean case to utils

- src/pages/organization/[id]/components/OrganizationHeader.tsx
https://gfw.atlassian.net/browse/TM-2066
> [TM-2066] Remove organization description from header

- src/connections/SitePolygons.ts
- src/hooks/useSitePolygonsHectares.ts
- src/pages/dashboard/hooks/useDashboardData.ts
https://gfw.atlassian.net/browse/TM-2087
> [TM-2087] use research service for projects in dashboard

- src/connections/BoundingBox.ts
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
- src/pages/dashboard/hooks/useDashboardData.ts
https://gfw.atlassian.net/browse/TM-2034
top trees planted deprecated and use project entity data
> [TM-2034] top trees planted v3

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/AttributeInformation.tsx
- src/admin/modules/impactStories/components/ImpactStoryForm.tsx
- src/admin/modules/user/components/UserShow.tsx
- src/components/elements/MapPolygonPanel/AttributeInformation.tsx
- src/pages/organization/[id]/components/edit/getEditOrganisationSteps.ts
- src/yup.locale.ts
https://gfw.atlassian.net/browse/TM-581
> [TM-581] Update date format to DD/MM/YYYY and set language to en-GB

- src/pages/dashboard/hooks/useDashboardData.ts
https://gfw.atlassian.net/browse/TM-2152
> [TM-2152] wait till allprojects

- src/connections/SitePolygons.ts
- src/hooks/useSitePolygonsHectares.ts
Add hook, and missing filter for statuses
> [TM-2139] add hook for getting all pages of sitepolygons

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/AttributeInformation.tsx
- src/components/elements/MapPolygonPanel/AttributeInformation.tsx
- src/constants/polygonDropdownOptions.ts
https://gfw.atlassian.net/browse/TM-2189
> [TM-2189] grassland target land use

- src/admin/components/ResourceTabs/InformationTab/components/InformationTabRow.tsx
- src/helpers/customForms.ts
https://gfw.atlassian.net/browse/TM-2191
remove error from admin on sites that have the update_request attribute set.
> [TM-2191] add parser from string and remove react-if

- src/pages/dashboard/components/HeaderDashboard.tsx
- src/pages/dashboard/hooks/useDashboardData.ts
- src/pages/dashboard/index.page.tsx
- src/pages/dashboard/project-list/index.page.tsx
https://gfw.atlassian.net/browse/TM-2126
> [TM-2126] replace project list with endpoint from v3

- src/admin/modules/organisations/components/OrganisationShow.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2212)
> [TM-2212] wait until the record is available in org actions

- src/admin/components/ResourceTabs/MonitoredTab/components/DataCard.tsx
- src/admin/components/ResourceTabs/MonitoredTab/components/MonitoredDataMap.tsx
- src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
- src/components/elements/Map-mapbox/components/MediaPopup.tsx
- src/components/elements/Map-mapbox/utils.ts
fix edit attributes in modal media https://gfw.atlassian.net/browse/TM-2216
> [TM-2216] edit attributes media on map

- src/components/elements/Inputs/Dropdown/RHFDropdown.tsx
https://gfw.atlassian.net/browse/TM-2197
> [TM-2197] Pass the form hook down to the display component.

- src/admin/components/ResourceTabs/MonitoredTab/components/DataCard.tsx
- src/admin/components/ResourceTabs/MonitoredTab/components/TreesLossBarChart.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2201)
> [TM-2201] update years

- src/admin/components/ResourceTabs/InformationTab/components/ReportInformationAside/HighLevelMetrics.tsx
- src/generated/v3/entityService/entityServiceConstants.ts
- src/generated/v3/entityService/entityServiceSchemas.ts
- src/pages/reports/project-report/tabs/TFSocioeconomic.tsx
https://gfw.atlassian.net/browse/TM-2198
> [TM-2198] Be more selective about which jobs collections are shown

- src/pages/applications/[id].page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2215)
> [TM-2215] add router locale for application form

- src/generated/v3/entityService/entityServiceSchemas.ts
- src/pages/reports/project-report/tabs/UploadedFiles.tsx
https://gfw.atlassian.net/browse/TM-2115
> [TM-2115] add new collection name options in media

- src/admin/components/ResourceTabs/ChangeRequestsTab/ChangeRow.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2230)
> [TM-2230] form demographic bug

- src/admin/modules/application/components/ApplicationsExportModal.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2218)
> [TM-2218] add light param

- src/generated/v3/researchService/researchServiceSchemas.ts
- src/pages/dashboard/hooks/useDashboardData.ts
https://gfw.atlassian.net/browse/TM-2206
> [TM-2206] add lat long from DB for site polygons centroids

- src/components/extensive/WizardForm/FormSummaryRow.tsx
https://gfw.atlassian.net/browse/TM-2258?atlOrigin=eyJpIjoiMTYxNDk5YmE3YjM2NDI1MDg0YjE0Zjc3NGFkY2UyMDgiLCJwIjoiaiJ9
> [TM-2258] fix approve project

- src/admin/apiProvider/dataProviders/financialReportDataProvider.ts
- src/admin/modules/financialReports/components/FinancialReportsList.tsx
- src/generated/apiComponents.ts
[Task Link](https://gfw.atlassian.net/browse/TM-2146)
> [TM-2146] add export funcionality

- src/components/extensive/ActionTracker/ActionTrackerCardRow.tsx
- src/components/extensive/ActionTracker/__snapshots__/ActionTracker.stories.storyshot
- src/components/extensive/ActionTracker/__snapshots__/ActionTrackerCardRow.stories.storyshot
- src/components/extensive/ActionTracker/cards/__snapshots__/ApplicationsCard.stories.storyshot
- src/constants/options/__snapshots__/fundingTypes.test.ts.snap
[Task Link](https://gfw.atlassian.net/browse/TM-2261)
> [TM-2261] regression due showing up

- src/components/elements/Inputs/Map/RHFMap.tsx
- src/components/elements/Map-mapbox/Map.tsx
- src/pages/applications/request-more-information/[id].page.tsx
call correct boundingbox for project pitches in application. 
Delete the cache for boundingbox after the application has updated the polygon.
> [TM-2232] store polygon

- src/pages/reports/financial-report/[uuid]/tabs/Overview.tsx
> [TM-2263] add hasData validate

- src/connections/DashboardHectareRestoration.ts
- src/generated/v3/dashboardService/dashboardServiceComponents.ts
- src/generated/v3/dashboardService/dashboardServiceConstants.ts
- src/generated/v3/dashboardService/dashboardServiceSchemas.ts
- src/generated/v3/dashboardService/dashboardServiceSelectors.ts
- src/hooks/useSitePolygonsHectares.ts
- src/pages/dashboard/hooks/useDashboardData.ts
- src/utils/dashboardUtils.ts
https://gfw.atlassian.net/browse/TM-2125
> [TM-2125] migration hectares under restoration using v3 endpoint

- src/admin/modules/application/context/export.provider.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2218)
> [TM-2218] update export provider to applications controller

- src/admin/components/ResourceTabs/HistoryTab/components/FinancialExchangeItem.tsx
- src/admin/components/ResourceTabs/HistoryTab/components/FinancialExchangeSection.tsx
- src/components/elements/Inputs/FinancialTableInput/RHFFinancialIndicatorTable.tsx
- src/components/elements/Inputs/FinancialTableInput/types.ts
- src/pages/reports/financial-report/[uuid]/tabs/Overview.tsx
- src/utils/financialReport.ts
[Task Link](https://gfw.atlassian.net/browse/TM-2280)
> [TM-2280] add exchange_rate field to financial indicator table

- src/components/elements/Map-mapbox/Map.tsx
- src/components/elements/Map-mapbox/MapControls/EditControl.tsx
- src/components/elements/Map-mapbox/MapControls/TrashButton.tsx
- src/components/elements/Map-mapbox/hooks/useMap.ts
- src/styles/extended-utilities.css
https://gfw.atlassian.net/browse/TM-2210
> [TM-2210] add trash button

- src/components/elements/Inputs/FinancialTableInput/RHFFinancialIndicatorTable.tsx
- src/components/elements/Inputs/FinancialTableInput/types.ts
[Task Link](https://gfw.atlassian.net/browse/TM-2280)
> [TM-2280] Reorder document column

- src/components/elements/Inputs/FinancialTableInput/RHFFinancialIndicatorTable.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2280)
> [TM-2280] add exchange rate field to financial indicators 

- src/admin/components/ResourceTabs/HistoryTab/components/FundingSourcesSection.tsx
- src/components/elements/Inputs/DataTable/DataTable.tsx
- src/components/elements/Inputs/DataTable/RHFFundingTypeDataTable.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2307)
> [TM-2307] add pagination to funding source

- src/components/elements/Cards/FundingCard/FundingCard.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2260)
> [TM-2260] add status action conditional

- src/components/elements/Inputs/FinancialTableInput/RHFFinancialIndicatorTable.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2305)
> [TM-2305] update header text to current ratio columns

- src/pages/reports/financial-report/[uuid]/tabs/Overview.tsx
[Task link](https://gfw.atlassian.net/browse/TM-2312)
> [TM-2312] change Financial Documents -> Net Profit By Year

- src/pages/reports/nursery-report/[uuid].page.tsx
- src/pages/reports/project-report/[uuid].tsx
[task link](https://gfw.atlassian.net/browse/TM-2292)
> TM-2292: Gallery images not loading correctly (Admin & PD view)

- src/pages/applications/request-more-information/[id].page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2328)
> [TM-2328] add missing lang query param when gathering application info

- src/pages/applications/components/ApplicationStatus.tsx
- src/pages/applications/request-more-information/[id].page.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2328)
> [TM-2328] use translated feedback fields

- src/pages/reports/financial-report/[uuid]/components/FinancialStackedBarChart.tsx
- src/utils/financialReport.ts
[Task Link](https://gfw.atlassian.net/browse/TM-2311)
> [TM-2311] Ensure Net Profit Shows Negative on Pop-up

- src/components/elements/MapPolygonPanel/ChecklistInformation.tsx
- src/components/elements/MapPolygonPanel/MapMenuPanelItem.tsx
- src/components/elements/MapSidePanel/MapSidePanel.tsx
- src/components/extensive/Modal/ModalSubmit.tsx
- src/hooks/useIsAdmin.ts
- src/hooks/useMessageValidations.ts
https://gfw.atlassian.net/browse/TM-2359
> [TM-2359] add label validation for planting status for admin

- src/components/elements/Inputs/FinancialTableInput/RHFFinancialIndicatorTable.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2327)
> [TM-2327] add missing translations for table

- src/components/extensive/DemographicsCollapseGrid/DemographicsRow.tsx
https://gfw.atlassian.net/browse/TM-1274
> [TM-1274] Small updates to workday table UI

- src/pages/applications/components/ApplicationStatus.tsx
This PR contains message improvements described in the comments in:
https://gfw.atlassian.net/browse/TM-2357
> [TM-2357] fix: improve clarity in draft status message for applications

- src/components/elements/Inputs/Map/RHFMap.tsx
https://gfw.atlassian.net/browse/TM-2397
> [TM-2397] Validate polygon in application

- src/admin/apiProvider/dataProviders/userDataProvider.ts
- src/admin/modules/form/components/FormList.tsx
- src/admin/modules/fundingProgrammes/components/FundingProgrammeList.tsx
- src/admin/modules/reportingFramework/components/ReportingFrameworkList.tsx
- src/admin/modules/user/components/UserList.tsx
- src/generated/apiComponents.ts
- src/generated/v3/userService/userServiceSchemas.ts
https://gfw.atlassian.net/browse/TM-2426
> [TM-2426] Remove user export.

- src/admin/components/ResourceTabs/InformationTab/index.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2439)
> [TM-2439] add ALL_TF for replanting data

- src/admin/apiProvider/dataProviders/applicationDataProvider.ts
- src/admin/apiProvider/utils/localeExtractor.ts
[Task Link](https://gfw.atlassian.net/browse/TM-2421)
> [TM-2421] add locale to admin application provider

- src/components/extensive/Tables/TreeSpeciesTable/hooks.ts
[Task Link](https://gfw.atlassian.net/browse/TM-2448)
> [TM-2448] add projectReports for noGoal

- src/components/elements/Inputs/FileInput/FileCardContent.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2353)
> [TM-2353] add missing transifex wrapper

- src/components/elements/Inputs/TreeSpeciesInput/TreeSpeciesInput.tsx
- src/components/extensive/Tables/TreeSpeciesTable/hooks.ts
- src/generated/v3/entityService/entityServiceSchemas.ts
https://gfw.atlassian.net/browse/TM-2449
Build will fail until the [v3 update](https://github.com/wri/terramatch-microservices/pull/301) has been merged and deployed
> [TM-2449] When prepopulating report species, include all establishment species.

- src/admin/modules/organisations/components/OrganisationEdit.tsx
- src/generated/apiComponents.ts
- src/generated/apiRequestBodies.ts
- src/generated/apiSchemas.ts
- src/pages/organization/[id]/components/edit/getEditOrganisationSteps.ts
- src/pages/organization/[id]/components/financial/FinancialInformation.tsx
- src/pages/organization/[id]/components/financial/FinancialTabContent.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2432)
> [TM-2432] revert changes

- src/admin/components/ResourceTabs/MonitoredTab/components/HeaderMonitoredTab.tsx
- src/admin/components/ResourceTabs/MonitoredTab/hooks/useMonitoredData.ts
- src/components/extensive/Modal/ModalRunAnalysis.tsx
- src/generated/apiComponents.ts
- src/generated/apiSchemas.ts
https://gfw.atlassian.net/browse/TM-2483
> [TM-2483] add rerun button in the indicator run analysis modal

- src/admin/components/ResourceTabs/MonitoredTab/components/DataCard.tsx
https://gfw.atlassian.net/browse/TM-2483
> [TM-2483] include neotropical in ecoregion table

- src/utils/MonitoredIndicatorUtils.ts
https://gfw.atlassian.net/browse/TM-2483
> [TM-2483] Update region categories

- src/admin/components/ResourceTabs/MonitoredTab/components/MonitoredDataMap.tsx
- src/admin/components/ResourceTabs/MonitoredTab/hooks/useMonitoredData.ts
- src/components/extensive/Tables/SitePolygonsTable.tsx
- src/utils/MonitoredIndicatorUtils.ts
https://gfw.atlassian.net/browse/TM-2483
> [TM-2483] show only approved polygons in indicators tables and graphs

- src/components/elements/Cards/ProjectCard/ProjectCard.tsx
- src/components/elements/ServerSideTable/ConnectionTable.tsx
- src/components/elements/ServerSideTable/ServerSideTable.tsx
- src/components/elements/TableFilters/TableFilter.tsx
- src/components/extensive/Tables/SitesTable.tsx
- src/helpers/api.ts
[task link](https://gfw.atlassian.net/browse/TM-2430)
> [TM-2430]  Site search bar not working (PD)

- src/pages/applications/request-more-information/success/[id].page.tsx
[task link](https://gfw.atlassian.net/browse/TM-2472)
> [TM-2472] Update success page text for resubmitted applications

- src/admin/components/AppBar.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2117)
> [TM-2117] add MenuItemLink for Logout

- src/admin/components/AppBar.tsx
> [TM-2117] adjust admin logout landing page 

- src/pages/organization/[id]/components/overview/TeamAndResources.tsx
https://gfw.atlassian.net/browse/TM-2508
> [TM-2508] change reference for leaderships

- src/components/extensive/WizardForm/FormSummaryRow.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2481)
> [TM-2481] add basic table display for profit analysis

- src/constants/dashboardConsts.ts
- src/constants/options/__snapshots__/landUseType.test.ts.snap
- src/constants/options/landUseType.ts
- src/pages/dashboard/charts/MultiLineChart.tsx
- src/pages/dashboard/components/SecDashboard.tsx
- src/utils/dashboardUtils.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1748)
> [TM-1748] add missing strings

- src/admin/modules/disturbanceReport/components/DisturbanceReport.tsx
- src/components/elements/Inputs/DataTable/RHFDisturbanceReportEntries.tsx
- src/components/extensive/DisturbanceReportEntries/__snapshots__/RHFDisturbanceReportEntries.stories.storyshot
- src/components/extensive/WizardForm/DisturbanceSiteAffectedInput.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-2366)
> [TM-2366] building out disturbance report

- src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/components/SinglePolygonValidation.tsx
- src/components/elements/Map-mapbox/MapControls/CheckIndividualPolygonControl.tsx
- src/components/elements/Map-mapbox/MapControls/CheckPolygonControl.tsx
- src/components/elements/Map-mapbox/MapControls/ProcessBulkPolygonsControl.tsx
- src/components/extensive/Modal/ModalFixOverlaps.tsx
- src/utils/polygonFixValidation.ts
https://gfw.atlassian.net/browse/TM-2537
> [TM-2537] add messages for clipping polygon function
