wri/wri-terramatch-website

src/pages/index.page.tsx
The "learn more" link now has different URLs based on language, so the URL is now a transifex string.
=> [TM-568] Translate the "learn more" link.

src/admin/components/ResourceTabs/ChangeRequestsTab/ChangeRequestsTab.tsx
https://gfw.atlassian.net/browse/TM-595
BE PR: https://github.com/wri/wri-terramatch-api/pull/33
Because the "draft" status on update requests was never really implemented, the Admin UI wasn't dealing with it correctly. This PR has two important updates:
* The "status" field on the change request correctly shows "draft" instead of "-"
* The buttons to approve/reject/request information are disabled when in the "draft" state, allowing the PD to finish updating and submitting it before the admin takes action on it.
=> [TM-595] Display the "draft" status on UpdateRequests correctly.

.gitignore, src/generated/apiComponents.ts, src/generated/apiRequestBodies.ts, src/generated/apiSchemas.ts, src/pages/project/[uuid]/reporting-task/[reportingTaskUUID].page.tsx
https://gfw.atlassian.net/browse/TM-561
BE PR: https://github.com/wri/wri-terramatch-api/pull/43
This PR is pretty minor, just supporting some changes on the BE PR. Two things to note here:
* The API hadn't been regenerated in some time, so there are a lot of changes there not related to this work
* I did a drive by bug fix on the task page when clicking the "nothing to report" button. The row would update, but the "nothing to report" button would still be visible until the page was refreshed. That wasn't part of this ticket, but it was an easy fix so I got that done here as well.
=> [TM-561] Unify status logic

src/pages/entity/[entityName]/edit/[uuid]/index.page.tsx
https://gfw.atlassian.net/browse/TM-683
Forms weren't fetching available update requests in all cases, and even when they were fetching them, the content of the update request wasn't being displayed. This didn't matter before an earlier fix because there was no "save and continue" functionality for update requests that worked until the draft status was implemented. 
BE PR: https://github.com/wri/wri-terramatch-api/pull/51
=> [TM-683] Use the update request data if available in edit mode.

src/pages/project/[uuid]/reporting-task/[reportingTaskUUID].page.tsx
https://gfw.atlassian.net/browse/TM-734
The previous behavior skipped showing the PD the feedback that is requested before taking them to edit mode. Implementing the modal that is used on the report landing page in this scenario on the tasks page would have been a bigger lift both in engineering effort and in network traffic because while the report/update request status is known on the task page, the API that's used to populate that page doesn't include any feedback text and adding it in the BE would have taken some additional effort as well. So, we simply take the user to the report landing page where they can follow the usual feedback flow.
=> [TM-734] Send the PD to the report landing page when feedback is requested

src/pages/project/[uuid]/reporting-task/[reportingTaskUUID].page.tsx
https://gfw.atlassian.net/browse/TM-734
The first change is a simple copy edit from feedback on the original PR for this ticket. The second is a behavior change to what gets shown in the "status" column, covering a corner case that we missed in the initial bug bash.
=> [TM-734] Tweaks to the report lines in the task page

next.config.js
This isn't strictly related to TM-803, but was a nice local dev enhancement I added while testing it. This allows local environments to get image uploads working by adding this to their `.env`:
```
IMAGE_DOMAINS = 'localhost'
```
=> [TM-803] Allow local dev environments to customize the next image domains

src/components/elements/Inputs/WorkdaysInput/RHFWorkdaysTable.tsx, src/components/extensive/WizardForm/FieldMapper.tsx, src/components/extensive/WizardForm/types.ts, src/components/extensive/WizardForm/utils.ts
[BE PR](https://github.com/wri/wri-terramatch-api/pull/196)
As can be seen on the BE PR, this didn't end up needing much FE work because I mapped the redirection of this field onto the regular linked fields system. However, we weren't correctly honoring `required` on child questions of conditionals, so I've fixed that in this PR.
=> [TM-913] Store description on workdays

src/components/elements/Cards/ProjectCard/ProjectCard.tsx
[Task](https://gfw.atlassian.net/browse/TM-936)
=> feat: TM-936 change hbf -> Harit Bharat Fund to my projects page

src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx, src/components/elements/Map-mapbox/Map.d.ts, src/components/elements/Map-mapbox/Map.tsx, src/components/elements/Map-mapbox/components/AdminPopup.tsx, src/components/elements/Map-mapbox/utils.ts, src/components/elements/TooltipMap/TooltipMap.tsx, src/components/extensive/EntityMapAndGalleryCard/EntityMapAndGalleryCard.tsx, src/context/sitePolygon.provider.tsx
Please check if your PR fulfills the following requirements:
Please check the type of change your PR introduces:
Currently, the gallery for projects and sites does not display any map or location data.
A new map component or section has been added to the gallery page for projects and sites.
- This map will display the geographic locations of the various projects and sites featured in the gallery.
- Users can now visually see where each project or site is located on the map, providing additional context and information.
- The map include markers and polygons.
- Clicking on a specific location marker provides more details about that particular polygon
=> Add gallery maps

src/admin/modules/application/components/ApplicationList.tsx, src/admin/modules/form/components/FormList.tsx, src/admin/modules/fundingProgrammes/components/FundingProgrammeList.tsx, src/admin/modules/nurseries/components/NurseriesList.tsx, src/admin/modules/nurseryReports/components/NurseryReportsList.tsx, src/admin/modules/organisations/components/OrganisationsList.tsx, src/admin/modules/pitch/components/PitchesList.tsx, src/admin/modules/projectReports/components/ProjectReportsList.tsx, src/admin/modules/projects/components/ProjectsList.tsx, src/admin/modules/reportingFramework/components/ReportingFrameworkList.tsx, src/admin/modules/siteReports/components/SiteReportsList.tsx, src/admin/modules/sites/components/SitesList.tsx, src/admin/modules/user/components/UserList.tsx, src/styles/custom-admin-page-styles.css
Please check if your PR fulfills the following requirements:
Please check the type of change your PR introduces:
Issue Number: N/A
Currently, the list views for various modules are using outdated designs that do not provide the best user experience. The designs lack modern UI elements, are not fully responsive, and do not leverage the latest features available in our component library.
- Updated the list views for the following modules to align with the new design guidelines:
- User List
- Organisations List
- Pitches List
- Funding Programmes List
- Applications List
- Forms List
- Projects List 
- Sites List 
- Nurseries List 
- Project Reports List
- Site Reports List
- Nursery Reports List
=> [TM-853] Admin UI Epic

src/components/extensive/WizardForm/index.tsx, src/components/extensive/WizardForm/utils.ts, src/pages/entity/[entityName]/edit/[uuid]/index.page.tsx
https://gfw.atlassian.net/browse/TM-739
=> [TM-739] Improve the defaults for which form step to start on in WizardForm

src/pages/reports/site-report/[uuid].page.tsx
https://gfw.atlassian.net/browse/TM-754
=> [TM-754] Display tree and seeding totals on the site report page.

src/components/elements/ServerSideTable/ServerSideTable.tsx, src/components/extensive/Pagination/index.tsx, src/components/extensive/Tables/TreeSpeciesTable.tsx, src/hooks/useProcessRecordData.ts, src/pages/reports/site-report/[uuid].page.tsx
https://gfw.atlassian.net/browse/TM-754
=> [TM-754] Some bug fixes for the site report trees table.

src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx, src/components/elements/Map-mapbox/Map.tsx, src/components/elements/Map-mapbox/hooks/useMap.ts, src/components/elements/Map-mapbox/utils.ts, src/components/elements/MapPolygonPanel/AttributeInformation.tsx, src/components/elements/MapPolygonPanel/ChecklistInformation.tsx, src/components/elements/MapPolygonPanel/MapEditPolygonPanel.tsx, src/components/elements/MapPolygonPanel/MapPolygonCheckPanelItem.tsx, src/components/elements/MapPolygonPanel/MapPolygonCkeckPanel.tsx, src/components/elements/MapPolygonPanel/MapPolygonPanel.stories.tsx, src/components/elements/MapPolygonPanel/MapPolygonPanel.tsx, src/components/elements/MapPolygonPanel/MapPolygonPanelItem.tsx, src/components/elements/MapPolygonPanel/MapPolygonSitePanel.tsx, src/components/elements/MapPolygonPanel/VersionInformation.tsx, src/components/elements/MapSidePanel/MapSidePanel.stories.tsx, src/components/elements/MapSidePanel/MapSidePanel.tsx, src/components/elements/MapSidePanel/MapSidePanelItem.tsx, src/pages/project/[uuid]/components/OverviewMapArea.tsx, src/pages/project/[uuid]/components/ProjectArea.tsx, src/pages/project/[uuid]/tabs/Overview.tsx, src/pages/site/[uuid]/components/MockedData.ts, src/pages/site/[uuid]/components/SiteArea.tsx, src/pages/site/[uuid]/tabs/Overview.tsx
https://gfw.atlassian.net/browse/TM-874
=> [TM-874] site profile non monitoring partner

src/hooks/AuditStatus/useAuditLogActions.ts, src/pages/project/[uuid]/tabs/Overview.tsx, src/pages/site/[uuid]/tabs/Overview.tsx
There is not task related, just some requirement to display the status diagram on site profile.
=> feat: add status diagram on site and project profile

src/components/extensive/WizardForm/FormSummaryRow.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-997) TM-997
[Task Link](https://gfw.atlassian.net/browse/TM-988) TM-988
=> [TM-997] Fix: Ensure "record.uuid" is safely accessed in getSiteBbox function

src/components/elements/Inputs/WorkdaysInput/RHFWorkdaysTable.tsx
Reports with an active update request from before the transition to the new demographics system have data in an unexpected shape. This null check better handles those cases.
https://gfw.atlassian.net/browse/TM-1137
=> [TM-1137] Better null handling for old report update requests.

src/admin/components/EntityEdit/EntityEdit.tsx, src/admin/components/ResourceTabs/ChangeRequestsTab/ChangeRequestsTab.tsx, src/admin/components/ResourceTabs/InformationTab/index.tsx, src/admin/modules/application/components/ApplicationTabs.tsx, src/helpers/customForms.ts, src/hooks/useGetCustomFormSteps/useGetCustomFormSteps.ts, src/pages/entity/[entityName]/edit/[uuid]/EditEntityForm.tsx
https://gfw.atlassian.net/browse/TM-1415
The problem here is that yesterday I tried to pull `framework_key` off of the `entity` in  `getFieldValidation` because workday validation now depends on knowing what kind of framework we're in. However, `entity` doesn't have `framework_key`, so that fix was invalid. To make matters more complicated, `getFieldValidation` is called in some contexts that are surrounded by a FrameworkContext, and in some that are not. So, we now have to accept `framework` optionally and pass it in when it's available.
=> [TM-1415] Provide the framework to getCustomFormSteps when possible.

src/components/elements/Inputs/WorkdaysInput/RHFWorkdaysTable.tsx
https://gfw.atlassian.net/browse/TM-1442
This applies the same fix as the [other PR](https://github.com/wri/wri-terramatch-website/pull/619), this time for hotfix.
=> [TM-1442] Pass all extra props to the input wrapper and avoid adding a second title to the workday grid

src/components/elements/Map-mapbox/Map.tsx, src/components/elements/Map-mapbox/components/DashboardPopup.tsx, src/components/elements/Map-mapbox/utils.ts, src/pages/dashboard/components/TooltipGridMap.tsx
=> [TM-1343] learn more link

src/hooks/useDate.ts
https://gfw.atlassian.net/browse/TM-572
The issue was that the hook useDate is returning a reference everytime any state is updated, this for useMemo is change even if the other data haven't changed this reload the whole page.
Now memoizing the format function in the useDate will cache the function and just change when is needed.
=> [TM-572] "Nothing to report" selection bumps user to page 1 of reports

src/middleware.page.ts, src/pages/_app.tsx, src/pages/dashboard/components/HeaderDashboard.tsx, src/utils/MiddlewareMatcher.ts
https://gfw.atlassian.net/browse/TM-1486
=> [TM-1486] Provide access to dashboard for admin users

src/pages/project/[uuid]/reporting-task/[reportingTaskUUID].page.tsx
This fix the issue with the button trying to update a status that is not supposed to do and removing refetch to prevent re-render and control the state in the UI
=> [No Ticket] Issue with button and re-render in additional reports

src/components/generic/Layout/__snapshots__/MainLayout.stories.storyshot, src/components/generic/Navbar/__snapshots__/Navbar.stories.storyshot, src/components/generic/Navbar/navbarItems.ts
[Task url](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1464)
=> [TM-1464] Update TerraMatch homepage when dashboard launches

src/generated/apiFetcher.ts
After a 502 on getting job status, try 3 times .
=> [TM-1513] add attemps for delayed jobs

src/admin/apiProvider/dataProviders/userDataProvider.ts, src/admin/components/App.tsx, src/admin/modules/index.tsx, src/admin/modules/user/components/UserCreate.tsx, src/admin/modules/user/components/UserShowAside.tsx, src/generated/apiComponents.ts, src/generated/apiRequestBodies.ts, src/generated/apiSchemas.ts, src/pages/auth/set-password/[token].page.tsx, src/pages/auth/set-password/components/SetPasswordForm.tsx
https://gfw.atlassian.net/browse/TM-1385
Backend PR: https://github.com/wri/wri-terramatch-api/pull/590
=> [TM-1385] Admin create user funtionality

src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonReviewAside/index.tsx, src/admin/components/ResourceTabs/PolygonReviewTab/components/Polygons.tsx, src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
https://gfw.atlassian.net/browse/TM-1535
=> [TM-1535] loader count polygons

src/admin/components/ResourceTabs/MonitoredTab/components/DataCard.tsx, src/admin/components/ResourceTabs/MonitoredTab/components/HeaderMonitoredTab.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1425)
=> [TM-1425] add loading to analysis and date of analysis

src/admin/components/ResourceTabs/MonitoredTab/components/DataCard.tsx, src/admin/components/ResourceTabs/MonitoredTab/components/EcoRegionDoughnutChart.tsx, src/components/extensive/Modal/ModalRunAnalysis.tsx
[Task link](https://gfw.atlassian.net/browse/TM-1468?focusedCommentId=35233)
=> [TM-1468] clear style monitored

src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?assignee=712020%3Afdaeb363-5553-48e0-9d3c-0af051b4affb&selectedIssue=TM-1556)
=> [TM-1556] Admin Views: Add info icon text

src/admin/components/ResourceTabs/MonitoredTab/components/EcoRegionDoughnutChart.tsx
https://gfw.atlassian.net/browse/TM-1466
=> [TM-1466] change format in tootltip for doughnut chart

src/pages/dashboard/learn-more/index.page.tsx
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?assignee=712020%3Afdaeb363-5553-48e0-9d3c-0af051b4affb&selectedIssue=TM-1571)
=> [TM-1571] Text updates to the dashboard's "learn more" page

src/admin/components/ResourceTabs/MonitoredTab/components/MonitoredCharts.tsx, src/pages/dashboard/components/GraphicIconDashboard.tsx
https://gfw.atlassian.net/browse/TM-1467
=> [TM-1467] show tooltip over the land use type chart

src/components/extensive/WizardForm/FormHeader.tsx, src/components/extensive/WizardForm/index.tsx, src/pages/entity/[entityName]/edit/[uuid]/EditEntityForm.tsx
https://gfw.atlassian.net/browse/TM-1576
=> [TM-1576] Update form header content for site reports.

next.config.js
I've set the relevant env variables in Amplify, so this isn't strictly necessary but it's better to have the defaults be right.
=> [TM-1527] Update the sentry defaults.

src/admin/components/Fields/CustomChipField.tsx, src/admin/components/ResourceTabs/MonitoredTab/components/DataCard.tsx
[Task link](https://gfw.atlassian.net/browse/TM-1425?focusedCommentId=35426)
=> [TM-1425] fix error color tag in table monitored

src/components/elements/Inputs/TreeSpeciesInput/RHFTreeSpeciesInput.tsx, src/components/elements/Inputs/TreeSpeciesInput/TreeSpeciesInput.tsx, src/components/elements/Inputs/TreeSpeciesInput/__snapshots__/TreeSpeciesInput.stories.storyshot
https://gfw.atlassian.net/browse/TM-1580
=> [TM-1580] Respect the label specified in the form builder.

src/components/elements/Inputs/TreeSpeciesInput/RHFSeedingTableInput.tsx, src/components/elements/Inputs/TreeSpeciesInput/RHFTreeSpeciesInput.tsx, src/components/elements/Inputs/TreeSpeciesInput/TreeSpeciesInput.tsx, src/connections/EstablishmentTrees.ts, src/generated/v3/entityService/entityServiceSchemas.ts
https://gfw.atlassian.net/browse/TM-1581
https://gfw.atlassian.net/browse/TM-1582
This build will fail until the v3 PR is merged and deployed.
=> [TM-1581][TM-1582] Tree Species input bug fixes.

src/admin/components/ResourceTabs/PolygonReviewTab/index.tsx
[Task link](https://gfw.atlassian.net/jira/software/c/projects/TM/boards/40?selectedIssue=TM-1556)
=> [TM-1556] add text in tooltips polygon review

src/components/extensive/BlurContainer/BlurContainer.tsx, src/components/extensive/PageElements/Card/PageCard.tsx, src/constants/dashboardConsts.ts, src/pages/dashboard/charts/CustomLabelRestoration.tsx, src/pages/dashboard/components/SecDashboard.tsx, src/pages/dashboard/index.page.tsx, src/utils/dashboardUtils.ts
https://gfw.atlassian.net/browse/TM-1568
=> [TM-1568] change text for logged users

src/components/elements/Table/Table.tsx, src/generated/apiComponents.ts, src/generated/apiSchemas.ts, src/pages/project/[uuid]/reporting-task/[reportingTaskUUID].page.tsx
https://gfw.atlassian.net/browse/TM-1624
In a previous ticket, @Scriptmatico did some work to make the "nothing to report" button correctly disappear after clicking it. However, that implementation turned out to be insufficient because the rest of the row columns weren't updating to reflect the new status. At the time, he did a bunch of investigation into the problem, which goes all the way down to how data is cached in the v2 system and how the Table component chooses to reset its internal state (like current page index) when the data changes. In this PR I've done some work to get that system to behave more appropriately for a case where the table data for a single row may update as a normal consequence of page interaction.
[PHP PR](https://github.com/wri/wri-terramatch-api/pull/649) …
=> [TM-1624] Round 2 of updates to the nothing to report process

src/admin/components/ResourceTabs/MonitoredTab/components/DataCard.tsx, src/utils/MonitoredIndicatorUtils.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1575)
=> [TM-1575] adds dynamic description functionality

src/admin/components/ResourceTabs/AuditLogTab/components/AuditLogTable.tsx, src/admin/components/ResourceTabs/PolygonReviewTab/components/PolygonDrawer/PolygonDrawer.tsx, src/admin/components/ResourceTabs/PolygonReviewTab/components/Polygons.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1011)
=> [TM-1011] polygon status enable comments

src/components/extensive/Tables/TreeSpeciesTablePD.tsx, src/pages/site/[uuid]/tabs/GoalsAndProgress.tsx
[Task Link](https://gfw.atlassian.net/browse/TM-1613)
=> [TM-1613] show data to seed planting progress tab

src/admin/components/EntityEdit/EntityEdit.tsx, src/pages/entity/[entityName]/edit/[uuid]/EditEntityForm.tsx
https://gfw.atlassian.net/browse/TM-1810
I added the call to `defaults()` in a recent web PR so that update requests would update with new form field values when a form is changed. However, calling defaults() every render was causing the source data to change for `useNormalizedFormDefaultValue`, and that source data is an input to its own useMemo dependency array, so this was causing forms to lose data while the user is typing (see loom on attached ticket).
=> [TM-1810] Memoize the source data so we don't update on every render.

amplify.yml, next.config.js, postcss.config.js
https://gfw.atlassian.net/browse/TM-1863
The main things here were eliminating some build errors during the next build. I don't think that actually fixed the problem though.  The other thing I did was update Amplify to use a build image with the same node version we have configured locally (`20.11.1`), which does seem to have addressed the problem. The default image on Amplify appears to have been using Node 18
=> [TM-1863] Improve Amplify builds

src/connections/BoundingBox.ts
Make invalid params empty string. 
This was leading to console errors that we want to avoid.
=> [TM-2040] prevent unnecesary call for bouunding box

src/components/elements/Inputs/Dropdown/Dropdown.tsx, src/components/elements/Inputs/Dropdown/RHFDropdown.tsx, src/components/elements/Inputs/Dropdown/__snapshots__/Dropdown.stories.storyshot, src/components/elements/Map-mapbox/MapControls/SiteStatus.tsx
https://gfw.atlassian.net/browse/TM-2164
This bug came down to one main problem: there were several different ways the dropdown was tracking state. 
* `Dropdown` was already filtering out invalid options, so when `RHFDropdown` did the same thing, it was causing extra renders, sometimes with invalid data
* Tracking the "other" value and selected options in `useState` in `Dropdown` was causing a race condition that resulted in many extra renders, with the value getting sent up to react form overwriting the value of the `setSelected` state as soon as it roundtripped down to the component, thus removing the selection of the "other" option.
* When a multi choice dropdown had its checkbox ticket, it was calling `onChange` twice: once in the checkbox and once at the top level list.
The solution …
=> [TM-2164] Improve Dropdown performance and fix usage of "other" option.
